import '../../test-env.cjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {googleCollectors,normalizeReports,reportRequests,activityRequests,normalizeActivity,dateInZone,validateCredentials} from '../analytics.mjs';
import {collectSite,validateConfig} from '../collectors.mjs';
import {createMonitor} from '../server.mjs';
import {fixtureCollectors,workspace,removeWorkspace} from './fixture.mjs';
import {assessHealth,capacityTone,growth} from '../health.mjs';
import {MonitorSession} from '../session.mjs';
import {calendarPeriods} from '../periods.mjs';

function report(dims,metrics,values){return {dimensionHeaders:dims.map(name=>({name})),metricHeaders:metrics.map(name=>({name})),rows:values.map(([d,m])=>({dimensionValues:d.map(value=>({value})),metricValues:m.map(value=>({value:String(value)}))})),metadata:{timeZone:'Asia/Shanghai'}};}
function reports(){return [report(['dateRange'],['activeUsers','newUsers','screenPageViews','sessions'],[[['today'],[3,1,9,4]],[['previous'],[0,0,0,0]],[['current'],[12,4,80,21]]]),report(['date'],['activeUsers','newUsers','screenPageViews','sessions'],[[['20260923'],[9,2,20,10]],[['20260922'],[8,2,30,10]]]),report(['pagePath','pageTitle'],['screenPageViews'],[[['/','首页'],[50]]]),report(['sessionDefaultChannelGroup'],['sessions'],[[['Direct'],[15]]]),report(['deviceCategory'],['sessions'],[[['mobile'],[16]]])];}
function activityReports(){return [report(['dateRange'],['activeUsers','newUsers'],[[['last1'],[9,2]],[['last7'],[12,4]],[['last30'],[28,10]]]),report(['date'],['activeUsers','newUsers'],[[['20260923'],[9,2]]]),report(['isoYearIsoWeek'],['activeUsers','newUsers'],[[['202638'],[12,4]]]),report(['yearMonth'],['activeUsers','newUsers'],[[['202608'],[28,10]]])];}
test('真实谷歌空实时响应保留未知，不显示成零或吞掉损坏响应',async()=>{
  const credentials={type:'authorized_user',client_id:'synthetic-client',client_secret:'synthetic-secret',refresh_token:'synthetic-refresh'};
  let payload={kind:'analyticsData#runRealtimeReport'};
  const collect=googleCollectors({gaPropertyId:'123',gaCredentialsPath:'/synthetic'},{readFile:async()=>JSON.stringify(credentials),fetchImpl:async url=>Response.json(url.includes('oauth2')?{access_token:'synthetic',expires_in:3600}:payload)}),signal=new AbortController().signal;
  const empty=await collect.realtime(signal);assert.equal(empty.activeUsers,null);assert.match(empty.notice,/未返回实时人数/);
  payload={};await assert.rejects(collect.realtime(signal),/报表不完整/);
  payload=report([],['activeUsers'],[[[],[0]]]);assert.equal((await collect.realtime(signal)).activeUsers,0);
});
test('日周月直接查询周期去重；跨年 ISO 周与闰年月份正确，隐私缺口不补零',()=>{
  const query=activityRequests('2026-09-24');assert.equal(query.length,4);assert.deepEqual(query[0].dateRanges.map(r=>r.startDate),['2026-09-23','2026-09-17','2026-08-25']);
  assert.equal(query[2].dimensions[0].name,'isoYearIsoWeek');assert.equal(query[2].dateRanges[0].endDate,'2026-09-20');assert.equal(query[3].dateRanges[0].startDate,'2026-03-01');assert.equal(query[3].dateRanges[0].endDate,'2026-08-31');
  const value=normalizeActivity(activityReports(),'2026-09-24','Asia/Shanghai');assert.equal(value.rolling[7].activeUsers,12);assert.equal(value.trends.week.at(-1).activeUsers,12);assert.equal(value.trends.month.at(-1).activeUsers,28);assert.equal(value.trends.day.length,14);
  assert.equal(calendarPeriods('2021-01-05','week',1)[0].key,'202053');assert.equal(calendarPeriods('2024-03-10','month',1)[0].endDate,'2024-02-29');assert.equal(calendarPeriods('2026-09-21','week',1)[0].endDate,'2026-09-20');
  const raw=activityReports();raw[2].metadata.subjectToThresholding=true;const limited=normalizeActivity(raw,'2026-09-24','Asia/Shanghai');assert.equal(limited.trends.week[0].activeUsers,null);assert.equal(limited.trends.day[0].activeUsers,0);assert.match(limited.notices[0],/隐私/);
  raw[1].metadata.timeZone='UTC';assert.throws(()=>normalizeActivity(raw,'2026-09-24','Asia/Shanghai'),/口径/);
});

test('谷歌报表按整个周期去重，日期补齐，保留元数据和零基期',()=>{const data=normalizeReports(reports(),7,Date.parse('2026-09-23T17:00:00Z'));assert.equal(data.todayDate,'2026-09-24');assert.equal(data.current.activeUsers,12);assert.equal(data.daily.length,7);assert.equal(data.daily[0].activeUsers,0);assert.equal(data.daily.at(-1).activeUsers,9);assert.equal(data.today.screenPageViews,9);assert.equal(growth(12,0).direction,'new');assert.equal(growth(0,0).direction,'flat');assert.equal(growth(null,5),null);const raw=reports();raw[2].metadata.subjectToThresholding=true;assert.match(normalizeReports(raw,7).notices[0],/隐私/);assert.throws(()=>normalizeReports([],7));});
test('报表只有五个批量查询、完整周期比较，不用日人数相加',()=>{const q=reportRequests(30);assert.equal(q.length,5);assert.deepEqual(q[0].dateRanges.map(r=>[r.startDate,r.endDate]),[['30daysAgo','yesterday'],['60daysAgo','31daysAgo'],['today','today']]);assert.equal(q[2].dimensions[0].name,'pagePath');assert.equal(q[2].limit,'10');assert.throws(()=>reportRequests(8));assert.equal(dateInZone(Date.parse('2026-09-24T01:00:00Z'),'America/Los_Angeles'),'2026-09-23');});
test('服务账号仅请求只读权限，忽略文件内任意 token_uri，缓存授权且不泄露密钥',async()=>{
  const {privateKey,publicKey}=crypto.generateKeyPairSync('rsa',{modulusLength:2048}),credentials={type:'service_account',client_email:'test@synthetic.iam.gserviceaccount.com',private_key:privateKey.export({format:'pem',type:'pkcs8'}),token_uri:'https://evil.test'};
  const calls=[],fetchImpl=async(url,options)=>{calls.push(url);if(url.includes('oauth2')){const assertion=options.body.get('assertion'),parts=assertion.split('.'),payload=JSON.parse(Buffer.from(parts[1],'base64url'));assert.equal(payload.scope,'https://www.googleapis.com/auth/analytics.readonly');assert.equal(payload.aud,'https://oauth2.googleapis.com/token');assert.ok(crypto.verify('RSA-SHA256',Buffer.from(parts.slice(0,2).join('.')),publicKey,Buffer.from(parts[2],'base64url')));return Response.json({access_token:'synthetic-secret-token',expires_in:3600});}return Response.json(url.endsWith(':batchRunReports')?{reports:JSON.parse(options.body).requests.length===4?activityReports():reports()}:report([],['activeUsers'],[[[],[0]]]));};
  const collect=googleCollectors({gaPropertyId:'123',gaCredentialsPath:'/synthetic.json',analyticsDays:7},{fetchImpl,readFile:async()=>JSON.stringify(credentials)}),signal=new AbortController().signal;
  const result=await collect.analytics(signal),realtime=await collect.realtime(signal);assert.equal(result.current.activeUsers,12);assert.equal(realtime.activeUsers,0);assert.equal(calls.filter(x=>x.includes('oauth2')).length,1);assert.ok(!calls.some(x=>x.includes('evil')));assert.ok(!JSON.stringify(result).includes('secret'));assert.throws(()=>validateCredentials({type:'service_account',private_key:'bad'}));
});
test('未配置、权限不足和配额错误分别展示，不用零掩盖错误',async()=>{const signal=new AbortController().signal;const none=await googleCollectors({}).analytics(signal);assert.equal(none.status,'unconfigured');assert.equal(none.current,undefined);const creds={type:'authorized_user',client_id:'synthetic-client',client_secret:'synthetic-secret',refresh_token:'synthetic-refresh'};for(const [status,message] of [[403,/授权/],[429,/额度/],[500,/失败/]]){const collect=googleCollectors({gaPropertyId:'1',gaCredentialsPath:'/mock',analyticsDays:7},{readFile:async()=>JSON.stringify(creds),fetchImpl:async(url)=>url.includes('oauth2')?Response.json({access_token:'test',expires_in:3600}):Response.json({error:{message:'private detail'}},{status})});await assert.rejects(collect.analytics(signal),message);}for(const value of [{gaPropertyId:'G-ID'},{gaPropertyId:'1/evil'},{analyticsDays:1},{gaCredentialsPath:'relative'}])assert.throws(()=>validateConfig(value));});
test('真实阅读抽查只 GET，不增加浏览统计；依赖失败时标注未检查',async()=>{const calls=[],book='a'.repeat(24),chapter='b'.repeat(24);const fetchImpl=async(url,options)=>{calls.push({url,options});if(url==='https://example.test')return new Response('<html><title>Website</title></html>');return Response.json(url.endsWith('?limit=1')?[{id:url.includes('/chapters')?chapter:book}]:url.includes('/api/chapters/')?{content:'真实章节内容'}:{});};const value=await collectSite({site:'https://example.test'},new AbortController().signal,{fetchImpl});assert.equal(value.checks.filter(c=>c.status==='ok').length,4);assert.equal(calls.length,4);assert.ok(calls.every(c=>!c.options.method||c.options.method==='GET'));assert.ok(calls.every(c=>!c.url.includes('/views')));const failed=await collectSite({site:'https://example.test'},new AbortController().signal,{fetchImpl:async()=>Response.json({}, {status:503})});assert.equal(failed.checks[2].status,'skipped');assert.equal(failed.checks[0].status,'error');});
test('健康结果不能用正常旧值掩盖断线，单个进程内存上限也会提醒',async()=>{const collect=fixtureCollectors(),s=new MonitorSession(collect);await s.refresh();const snap=s.snapshot();snap.config={atlasLimitMiB:512};snap.modules.server.data.services=['test1-api.service','test1-web.service','nginx.service'].map(Id=>({Id,ActiveState:'active',MemoryCurrent:'10',MemoryMax:'100'}));assert.equal(assessHealth(snap).level,'good');assert.equal(capacityTone(80),'warning');assert.equal(capacityTone(90),'danger');snap.modules.server.data.services[0].MemoryCurrent='95';assert.ok(assessHealth(snap).issues.some(i=>i.level==='danger'&&i.title.includes('自身内存')));snap.modules.server.status='error';assert.ok(assessHealth(snap).resources.every(r=>r.id==='atlas'||r.tone==='unknown'));snap.modules.site.stale=true;assert.ok(assessHealth(snap).checks.every(c=>c.level==='unknown'));snap.config.atlasLimitMiB=null;assert.ok(assessHealth(snap).issues.some(i=>i.title.includes('容量余量')));await s.close();});
test('切换日期取消旧请求，迟到数据不会串入新范围，暂停状态保留',async()=>{let resolve;const s=new MonitorSession({analytics:()=>new Promise(r=>resolve=r)});s.paused=true;const first=s.refresh('analytics');await Promise.resolve();const resetting=s.reset(['analytics'],{analytics:async()=>({days:7})});resolve({days:30});await first;await resetting;assert.equal(s.modules.analytics.data.days,7);assert.equal(s.paused,true);await s.close();});
test('授权文件只在本机保存，导出不包含授权内容或路径',async t=>{const root=workspace();t.after(()=>removeWorkspace(root));const app=await createMonitor({root,collect:fixtureCollectors(),start:false});t.after(()=>app.close());const headers={'x-monitor-token':app.token,'Content-Type':'application/json'};const credentials={type:'authorized_user',client_id:'synthetic-client',client_secret:'synthetic-secret',refresh_token:'synthetic-refresh'};const res=await fetch(app.baseUrl+'/api/analytics/credentials',{method:'POST',headers,body:JSON.stringify({propertyId:'123',credentials})});assert.equal(res.status,200);assert.equal(JSON.parse(fs.readFileSync(path.join(root,'.runtime/site-monitor/google-credentials.json'),'utf8')).type,'authorized_user');assert.ok(!JSON.stringify(app.snapshot()).includes('synthetic-secret'));const exported=await(await fetch(app.baseUrl+'/api/export',{method:'POST',headers,body:'{"format":"json"}'})).json();const raw=await(await fetch(app.baseUrl+'/api/report?name='+exported.name,{headers})).text();assert.ok(!raw.includes('gaCredentialsPath'));assert.ok(!raw.includes('synthetic-refresh'));assert.equal((await fetch(app.baseUrl+'/google-credentials.json')).status,404);});
