import '../../test-env.cjs';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {calendarPeriods,trendCounts} from '../periods.mjs';
export function workspace(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'site-monitor-test-'));execFileSync('git',['init','--quiet',root],{windowsHide:true});return root;}
export function removeWorkspace(root){const absolute=path.resolve(root);if(!absolute.startsWith(path.resolve(os.tmpdir())+path.sep)||!path.basename(absolute).startsWith('site-monitor-test-'))throw Error('Unsafe test path');fs.rmSync(absolute,{recursive:true,force:true});}
export function fixtureCollectors(){let n=0;return {
  server:async()=>({sampledAt:new Date(Date.now()+n++*15000).toISOString(),cpu:{idle:100+n*300,total:100+n*1000},cores:2,uptime:90000,load:[.2,.1,.1],memory:{total:4*1024**3,available:3*1024**3,swapTotal:2*1024**3,swapUsed:0},network:{rx:n*5000,tx:n*2000},disk:{total:40*1024**3,available:30*1024**3,free:30*1024**3,inodes:500000,freeInodes:400000},services:[{Id:'test1-api.service',ActiveState:'active',MemoryCurrent:'134217728',NRestarts:'0',MemoryMax:'805306368'}],api:{rss:134217728,databaseReady:true},backup:{status:'success',finishedAt:new Date().toISOString()},release:'synthetic-test-release'}),
  atlas:async()=>({sampledAt:new Date().toISOString(),pingMs:30,database:'synthetic_test',dataBytes:60*1024**2,indexBytes:8*1024**2,storageBytes:80*1024**2,objects:100000,collections:20,indexes:40,cluster:{logicalBytes:80*1024**2,databases:2}}),
  r2:async()=>({sampledAt:new Date().toISOString(),buckets:[{id:'chapters',bucket:'synthetic-chapters',label:'正文',status:'ok',latencyMs:50},{id:'covers',bucket:'synthetic-covers',label:'封面',status:'ok',latencyMs:40}]}),
  site:async()=>({sampledAt:new Date().toISOString(),status:200,latencyMs:200,url:'https://example.test',checks:['home','books','catalog','chapter'].map((id,i)=>({id,label:['网站首页','书籍列表','章节目录','章节正文'][i],status:'ok',latencyMs:120+i*35}))}),
  analytics:async()=>analyticsFixture(),
  realtime:async()=>({status:'connected',sampledAt:new Date().toISOString(),activeUsers:6}),
  business:async()=>businessFixture(),
  traffic:async()=>({status:'connected',mode:'observe',startedDate:'2026-09-01',ruleVersion:'fixture-v1',observationDays:2,reviewReady:false,views:Object.fromEntries(['raw','retained'].map(mode=>[mode,{...analyticsFixture().activity,today:{activeUsers:mode==='raw'?4:3,newUsers:2}}])),sessionCounts:{high:1,watch:2,insufficient:3},samples:[{day:'2026-09-23',score:85,classification:'high',signals:['speed','regular','noInteraction'],pages:40}]}),
};}
export function analyticsFixture(){const data={status:'connected',sampledAt:new Date().toISOString(),days:30,timeZone:'Asia/Shanghai',startDate:'2026-08-25',endDate:'2026-09-23',todayDate:'2026-09-24',activity:{endDate:'2026-09-23',rollingEndDate:'2026-09-24',rolling:{1:{activeUsers:21,newUsers:9},7:{activeUsers:91,newUsers:35},30:{activeUsers:328,newUsers:215}},trends:Object.fromEntries(Object.entries(trendCounts).map(([unit,count])=>[unit,calendarPeriods('2026-09-24',unit,count).map((p,i)=>({...p,activeUsers:8+i%7*3+Math.floor(i/3),newUsers:3+i%5+Math.floor(i/5)}))]))},current:{activeUsers:328,newUsers:215,screenPageViews:8264,sessions:721},previous:{activeUsers:210,newUsers:163,screenPageViews:5930,sessions:470},today:{activeUsers:21,newUsers:9,screenPageViews:470,sessions:39},daily:Array.from({length:30},(_,i)=>({date:new Date(Date.UTC(2026,7,25+i)).toISOString().slice(0,10),activeUsers:8+i%7*3+Math.floor(i/3),newUsers:3+i%5+Math.floor(i/5),screenPageViews:50+i*11,sessions:15+i})),pages:[{title:'九天小说站 - 热门小说',path:'/',views:2870},{title:'我的书架 - 九天小说站',path:'/bookshelf',views:1632},{title:'1984：从川菜馆开始 - 九天小说站',path:'/books/example',views:912},{title:'小说排行榜 - 九天小说站',path:'/ranking',views:731}],channels:[{name:'Organic Search',value:432},{name:'Direct',value:219},{name:'Referral',value:70}],devices:[{name:'mobile',value:512},{name:'desktop',value:186},{name:'tablet',value:23}],notices:[]};
  data.regions=Object.fromEntries([['china',.6]].map(([region,ratio])=>{
    const activity=structuredClone(data.activity);
    for(const row of [...Object.values(activity.rolling),...Object.values(activity.trends).flat()])for(const key of ['activeUsers','newUsers'])row[key]=Math.floor(row[key]*ratio);
    return [region,{status:'connected',sampledAt:data.sampledAt,activity}];
  }));data.cities={status:'connected',sampledAt:data.sampledAt,periods:Object.fromEntries([['day',1],['week',7],['month',30]].map(([unit,days])=>[unit,{startDate:new Date(Date.parse('2026-09-24T00:00:00Z')-(days-1)*86400000).toISOString().slice(0,10),endDate:'2026-09-24',notices:[],cities:['Shanghai','Beijing','Guangzhou','Shenzhen','Hangzhou','Chengdu','Wuhan','Nanjing','Berlin','London'].map((name,i)=>({id:String(i),name,region:'',country:i<8?'CN':i===8?'DE':'GB',activeUsers:(10-i)*days}))}]))};return data;
}
export function businessFixture(){return {sampledAt:new Date().toISOString(),days:30,timeZone:'Asia/Shanghai',startDate:'2026-08-25',endDate:'2026-09-23',todayDate:'2026-09-24',registrationHistory:calendarPeriods('2026-09-24','day',400).map((p,i)=>({date:p.date,newUsers:i%4})),totalUsers:136,unknownRegistrationDates:0,todayNewUsers:3,current:{newUsers:38,reads:5143},previous:{newUsers:24,reads:3910},daily:Array.from({length:30},(_,i)=>({date:new Date(Date.UTC(2026,7,25+i)).toISOString().slice(0,10),newUsers:i%4,reads:50+i*8})),topBooks:[{title:'1984：从川菜馆开始',views:721},{title:'绍宋',views:534},{title:'诡秘之主',views:311}],bookmarks:[{title:'绍宋',count:24},{title:'诡秘之主',count:18}],excludedBaseline:100000};}
