import '../../test-env.cjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import {acquire, bindReadingEdition} from '../core.mjs';
import {atomicWrite, readJson, hash} from '../storage.mjs';
import {formatChapterForExport} from '../titles.mjs';

test('file gaps preserve empty entries, require pinned reviews and block changed checkpoints', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'novel-file-gaps-'));
  const body = n => Array.from({length: 1000}, (_, i) => String.fromCodePoint(0x4e00 + n * 1100 + i)).join('');
  const garbled = body(2) + '\ue001\ue002\ue003'.repeat(10);
  const server = http.createServer((req, res) => {
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.end(req.url === '/book' ? '<h1>合成小说</h1><b>测试作者</b><nav>' + ['第一章 开始','第二章 乱码','第三章 后续','第四章 空章'].map((title,i)=>`<a href="/chapter-${i+1}.html">${title}</a>`).join('') + '</nav>' : `第一章 开始\n${body(1)}\n第二章 乱码\n${garbled}\n第三章 后续\n${body(3)}\n第四章 空章\n`);
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => {
    await new Promise(resolve => server.close(resolve));
    assert.equal(path.dirname(path.resolve(root)), path.resolve(os.tmpdir()));
    assert.match(path.basename(root), /^novel-file-gaps-/);
    fs.rmSync(root, {recursive: true, force: true});
  });
  const base = `http://127.0.0.1:${server.address().port}`;
  const spec = {version: 1, kind: 'txt', title: '合成小说', author: '测试作者', sourceUrl: base + '/book', delayMs: 200, retries: 0, metadata: {title: 'h1', author: 'b'}, resource: {url: base + '/text'}, catalog:{links:'nav a'}, chapter:{title:'h1',content:'article'}};
  const options = {stateDir: path.join(root, 'state'), outputDir: path.join(root, 'exports'), mode: 'download'};
  const first = await acquire(spec, options);
  assert.equal(first.completeAgainstSource, true);
  assert.equal(first.structuralPass, false);
  assert.equal(first.exportFile, null);
  assert.ok(first.issues.some(i => i.code === 'empty' && i.chapter === 4));
  const dir = path.join(options.stateDir, 'jobs', first.jobId), catalog = readJson(path.join(dir, 'catalog.json'));
  const raw = catalog.map(c => readJson(path.join(dir, 'chapters', hash(c.link) + '.json')).chapter);
  assert.equal(raw[3].content, '');
  assert.ok(raw[3].provenance[0].hash);
  const selected = positions => ({title: spec.title, author: spec.author, sourceUrl: spec.sourceUrl, chapters: positions.map((n, i) => ({...formatChapterForExport(raw[n-1]), chapter_number:i+1, sourceChapterNumber:n, sourceChapterUrl:raw[n-1].link}))});
  const file = path.join(options.outputDir, 'reviewed.json');
  const gap = (n, kind) => ({position:n, link:raw[n-1].link, contentHash:hash(raw[n-1].content), kind, reason:'逐项核实源文件缺陷', evidence:{url:base+'/text', checkedAt:new Date().toISOString(), detail:'完整文件与原始哈希均已保存'}});
  const review = {catalogHash:hash(catalog), reason:'保留其余原始次序', pairs:[], gaps:[gap(2,'garbled'),gap(4,'empty')]};
  const bind = r => bindReadingEdition(spec, file, {...options,sourceOrderReview:r});
  atomicWrite(file,selected([1,3]));
  await assert.rejects(bind({...review,gaps:[gap(2,'empty'),gap(4,'empty')]}),/非空正文/);
  await assert.rejects(bind({...review,gaps:[{...gap(2,'garbled'),contentHash:'wrong'},gap(4,'empty')]}),/哈希/);
  await assert.rejects(bind({...review,gaps:[{...gap(2,'garbled'),evidence:{}},gap(4,'empty')]}),/证据/);
  atomicWrite(file,selected([3]));
  await assert.rejects(bind({...review,gaps:[gap(1,'garbled'),...review.gaps]}),/普通正文/);
  atomicWrite(file,selected([1,3]));
  await bind(review);
  const accepted = await acquire(spec,options);
  assert.equal(accepted.structuralPass,true,JSON.stringify(accepted.failures));
  assert.equal(accepted.completeAgainstSource,false);
  assert.equal(accepted.completeSelectedScope,true);
  assert.equal(accepted.sourceGaps.length,2);
  assert.equal(readJson(path.join(dir,'chapters',hash(raw[1].link)+'.json')).chapter.content,garbled);
  const before = fs.readFileSync(file);
  await assert.rejects(acquire(spec,{...options,refresh:true}),/不能强制刷新/);
  const changed = {...raw[3],content:'新出现的正文必须重新核对'};
  atomicWrite(path.join(dir,'chapters',hash(changed.link)+'.json'),{chapter:changed,hash:hash(changed)});
  const blocked = await acquire(spec,options);
  assert.equal(blocked.structuralPass,false);
  assert.equal(blocked.exportFile,null);
  assert.deepEqual(fs.readFileSync(file),before);
});
