const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);
const $=s=>document.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=x=>typeof x==='number'&&Number.isFinite(x);
const number=x=>finite(x)?x.toLocaleString('zh-CN',{maximumFractionDigits:1}):'—';
function bytes(x){if(!finite(x))return '—';if(x===0)return '0 B';const units=['B','KiB','MiB','GiB','TiB'],i=Math.min(4,Math.max(0,Math.floor(Math.log(x)/Math.log(1024))));return `${(x/1024**i).toLocaleString('zh-CN',{maximumFractionDigits:i?2:0})} ${units[i]}`;}
const time=x=>x?new Date(x).toLocaleTimeString('zh-CN',{hour12:false}):'尚未获取';
const date=x=>x?new Date(x).toLocaleString('zh-CN',{hour12:false}):'尚未获取';
const pct=x=>finite(x)?`${x.toFixed(1)}%`:'—';
let state,page='overview',signature='',polling=false,toastTimer;
const labels={overview:['网站运行总览','资源余量、服务状态与本次运行趋势。'],server:['服务器','查看系统资源、运行进程与部署版本。'],atlas:['Atlas 数据库','区分业务库大小、集群总用量和配置的容量上限。'],r2:['R2 对象存储','轻量检查桶状态，按需盘点容量。'],reports:['报告与清理','按需保存，定期清理，控制本地空间。'],settings:['连接设置','沿用服务器现有配置，密钥和业务数据不下载到本地。']};
async function api(route,data){const res=await fetch('/api/'+route,{method:data===undefined?'GET':'POST',headers:{'x-monitor-token':token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw Error(result.error||'请求失败');return result;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5500);}
function status(m){if(!m)return ['neutral','等待采集'];if(m.busy&&!m.data)return ['neutral','正在连接'];if(m.status==='error')return ['error','连接失败'];if(m.stale)return ['warn','数据已过期'];if(m.data)return ['ok','已连接'];return ['neutral','等待采集'];}
const tag=(label,type='neutral')=>`<span class="tag ${type}">${esc(label)}</span>`;
function moduleTag(key){const m=state.modules[key];const [type,label]=status(m);return tag(label,type);}
function moduleNote(key){const m=state.modules[key];return m.error?`<div class="subtle-note warning">${esc(m.error)}${m.data?'；当前显示最后一次成功结果。':''}</div>`:m.stale?'<div class="subtle-note warning">当前数据已过期，数值仅供参考。</div>':'';}
function metric(label,value,detail,badge=''){return `<div class="metric-card"><div class="metric-label">${esc(label)}${badge}</div><div class="metric-value">${esc(value)}</div><div class="metric-detail">${esc(detail)}</div></div>`;}
function panel(title,body,aside='',caption=''){return `<section class="panel"><div class="panel-head"><div><h2>${esc(title)}</h2>${caption?`<div class="caption">${esc(caption)}</div>`:''}</div>${aside}</div>${body}</section>`;}
function details(rows){return `<div class="detail-list">${rows.map(([k,v])=>`<div class="detail-item"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`;}
function bar(label,used,total,detail=''){const ratio=finite(used)&&finite(total)&&total>0?100*used/total:null;return `<div class="capacity-row"><div class="labels"><span>${esc(label)}</span><span>${ratio===null?'未配置上限':pct(ratio)}</span></div><div class="progress"><div class="progress-bar ${ratio>90?'danger':ratio>80?'warning':''}" style="width:${ratio===null?0:Math.max(0,Math.min(100,ratio))}%"></div></div><div class="metric-detail">${esc(detail||`${bytes(used)} / ${bytes(total)}`)}</div></div>`;}
function chart(points,keys,colors,unit='%',fixedMax){
  if(points.filter(p=>keys.some(k=>finite(p[k]))).length<2)return '<div class="chart-empty">继续采样后显示本次趋势</div>';
  const data=points.slice(-180),w=650,h=210,left=42,right=10,top=13,bottom=29,max=fixedMax||Math.max(1,...data.flatMap(p=>keys.map(k=>finite(p[k])?p[k]:0)))*1.16;
  const first=data[0].at,last=data.at(-1).at,x=p=>left+(p.at-first)/Math.max(1,last-first)*(w-left-right),y=v=>top+(1-v/max)*(h-top-bottom);
  let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="本次运行趋势"><title>本次运行趋势；横轴为时间，纵轴单位 ${esc(unit)}</title>`;
  for(let i=0;i<=4;i++){const value=max*i/4,Y=y(value);svg+=`<line x1="${left}" y1="${Y}" x2="${w-right}" y2="${Y}" stroke="#edf2f2"/><text x="${left-8}" y="${Y+4}" text-anchor="end">${value>=1000?number(value/1000)+'k':number(value)}</text>`;}
  keys.forEach((key,i)=>{let move=true,d='';for(const p of data){if(!finite(p[key])||p.gap){move=true;continue;}d+=`${move?'M':'L'}${x(p).toFixed(1)},${y(p[key]).toFixed(1)} `;move=false;}svg+=`<path d="${d}" stroke="${colors[i]}" stroke-width="2.3" fill="none" stroke-linejoin="round"/>`;});
  svg+=`<text x="${left}" y="${h-4}">${time(first)}</text><text x="${w-right}" y="${h-4}" text-anchor="end">${time(last)}</text></svg>`;return svg;
}
function serviceRow(symbol,name,subtitle,badge){return `<div class="service-row"><div class="service-symbol">${symbol}</div><div class="service-copy"><strong>${esc(name)}</strong><p>${esc(subtitle)}</p></div>${badge}</div>`;}
function healthRows(){return serviceRow('↗','网站 HTTPS',state.modules.site.data?`${number(state.modules.site.data.latencyMs)} ms · ${time(state.modules.site.lastSuccess)}`:'等待公网检查',moduleTag('site'))+serviceRow('▤','VPS 服务器',`上次采集 ${time(state.modules.server.lastSuccess)}`,moduleTag('server'))+serviceRow('▥','MongoDB Atlas',state.modules.atlas.data?.database||'等待数据库响应',moduleTag('atlas'))+serviceRow('◇','Cloudflare R2',r2Summary(),r2Badge());}
function r2Summary(){const buckets=state.modules.r2.data?.buckets;if(!buckets)return '等待存储桶响应';return `${buckets.filter(b=>b.status==='ok').length} / ${buckets.length} 个桶可访问`;}
function r2Badge(){const m=state.modules.r2,b=m.data?.buckets;if(m.status==='error'||m.stale||!b)return moduleTag('r2');return b.every(x=>x.status==='ok')?tag('可访问','ok'):tag('需检查','warn');}
function freshness(key){return `最后成功 ${time(state.modules[key].lastSuccess)} · ${state.modules[key].interval/1000} 秒刷新`;}
function refreshButton(key){return `<button class="btn btn-outline-secondary" data-refresh="${key}">${state.modules[key].busy?'正在刷新…':'刷新'}</button>`;}
function overview(){const s=state.modules.server.data,a=state.modules.atlas.data,logical=a?.cluster?.logicalBytes??(a?a.dataBytes+a.indexBytes:null),disks=s?`${bytes(s.disk.available)} 可用 / ${bytes(s.disk.total)}`:'等待首次采样';
  const inventory=state.inventory.buckets,complete=inventory.length===2&&inventory.every(x=>x.complete),r2=complete?bytes(inventory.reduce((n,x)=>n+x.bytes,0)):'未盘点';
  return `<div class="metric-grid">${metric('服务器 CPU',pct(s?.cpuPercent),s?`${s.cores} 核 · ${s.cpuPercent===null?'等待第二次采样':'本次采样间隔利用率'}`:'等待连接',moduleTag('server'))}${metric('可用内存',bytes(s?.memory.available),s?`共 ${bytes(s.memory.total)} · 已用 ${pct(100*(1-s.memory.available/s.memory.total))}`:'等待连接')}${metric('Atlas 集群用量',bytes(logical),a?.cluster?'包含集群数据与索引':a?'仅业务库，集群指标不可用':'等待连接',moduleTag('atlas'))}${metric('R2 对象容量',r2,complete?'本次列表盘点结果，非计费统计':'进入 R2 页面按需盘点',r2Badge())}</div>
    <div class="two-columns">${panel('服务器资源趋势',chart(state.modules.server.history,['cpu','memory'],['#087f78','#8abbb2'],'%',100),'<div class="legend"><span><i style="background:#087f78"></i>CPU</span><span><i style="background:#8abbb2"></i>内存</span></div>','本次会话 · 最近 180 个采样点')}${panel('连接状态',healthRows())}</div>
    <div class="equal-columns">${panel('资源余量',bar('VPS 磁盘',s?s.disk.total-s.disk.available:null,s?.disk.total,disks)+bar('Atlas 容量',logical,state.config.atlasLimitMiB?state.config.atlasLimitMiB*1024**2:null,state.config.atlasLimitMiB?`上限 ${number(state.config.atlasLimitMiB)} MiB · 手动配置`:'在连接设置中填写套餐容量上限'))}${panel('本次检查',details([['监控开始',time(state.startedAt)],['当前部署',s?.release||'—'],['数据保存',`${state.storage.files.length} 份报告`],['本地报告占用',bytes(state.storage.bytes)],['采样策略',state.paused?'已暂停自动刷新':'仅程序打开期间'],['历史范围','每模块最多 1,440 点']]))}</div>`;
}
function serverPage(){const m=state.modules.server,s=m.data;return moduleNote('server')+`<div class="metric-grid">${metric('CPU 利用率',pct(s?.cpuPercent),s?`${s.cores} 核 · ${number(s.load[0])} 系统负载`:'等待采样',moduleTag('server'))}${metric('可用内存',bytes(s?.memory.available),s?`总内存 ${bytes(s.memory.total)}`:'—')}${metric('磁盘可用',bytes(s?.disk.available),s?`总空间 ${bytes(s.disk.total)}`:'—')}${metric('网络接收速率',s?.rxPerSecond===null||!s?'—':bytes(s.rxPerSecond)+'/s',s?`发送 ${s.txPerSecond===null?'采样中':bytes(s.txPerSecond)+'/s'}`:'等待两次采样')}</div>`+
    `<div class="equal-columns">${panel('CPU 与内存',chart(m.history,['cpu','memory'],['#087f78','#8abbb2'],'%',100),refreshButton('server'),freshness('server'))}${panel('网络流量',chart(m.history.map(p=>({...p,rx:finite(p.rx)?p.rx/1024:null,tx:finite(p.tx)?p.tx/1024:null})),['rx','tx'],['#087f78','#91aaa4'],'KiB/s'),'<div class="legend"><span>接收 / 发送 · KiB/s</span></div>','服务器非回环接口汇总')}</div>`+
    panel('网站服务',s?.services?.length?`<div class="table-wrap"><table class="table"><thead><tr><th>服务</th><th>状态</th><th>重启次数</th><th>进程内存</th><th>服务内存上限</th></tr></thead><tbody>${s.services.map(x=>`<tr><td class="text-mono">${esc(x.Id)}</td><td>${tag(x.ActiveState,x.ActiveState==='active'?'ok':'warn')}</td><td>${esc(x.NRestarts||'—')}</td><td>${/^[0-9]+$/.test(x.MemoryCurrent)&&Number(x.MemoryCurrent)<1e15?bytes(Number(x.MemoryCurrent)):'—'}</td><td>${/^[0-9]+$/.test(x.MemoryMax)&&Number(x.MemoryMax)<1e15?bytes(Number(x.MemoryMax)):'未设置'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="small-copy">服务状态尚未取得。</p>')+
    panel('系统与备份',details([['运行时长',s?`${Math.floor(s.uptime/86400)} 天 ${Math.floor(s.uptime%86400/3600)} 小时`:'—'],['交换空间已用',bytes(s?.memory.swapUsed)],['可用 inode',number(s?.disk.freeInodes)],['部署版本',s?.release||'—'],['API 内存',bytes(s?.api?.rss)],['API 数据库连接',s?.api?String(s.api.databaseReady):'未取得'],['备份清单状态',s?.backup?.status||'未取得'],['最近备份完成',date(s?.backup?.finishedAt||s?.backup?.createdAt)]]));}
function atlasPage(){const a=state.modules.atlas.data,logical=a?.cluster?.logicalBytes??(a?a.dataBytes+a.indexBytes:null);return moduleNote('atlas')+`<div class="metric-grid">${metric('集群逻辑大小',bytes(a?.cluster?.logicalBytes),'集群所有数据库的数据 + 索引',moduleTag('atlas'))}${metric('业务库数据',bytes(a?.dataBytes),a?.database||'等待连接')}${metric('业务库索引',bytes(a?.indexBytes),a?`${number(a.indexes)} 个索引`:'—')}${metric('数据库往返',a?`${number(a.pingMs)} ms`:'—','服务器到数据库的 Ping 耗时')}</div>`+
    `<div class="equal-columns">${panel('容量变化',chart(state.modules.atlas.history.map(p=>({...p,logical:finite(p.logical)?p.logical/1024**2:null})),['logical'],['#087f78'],'MiB'),refreshButton('atlas'),freshness('atlas'))}${panel('容量边界',bar('逻辑容量',logical,state.config.atlasLimitMiB?state.config.atlasLimitMiB*1024**2:null)+details([['数据库数量',number(a?.cluster?.databases)],['业务记录数',number(a?.objects)],['业务集合数',number(a?.collections)],['业务数据分配空间',bytes(a?.storageBytes)]]))}</div><div class="subtle-note">容量上限由你按实际套餐填写；物理分配空间不等于套餐逻辑用量。当前未接入 Atlas 管理 API，因此连接额度、操作量及七天传输量显示为“未接入”，不会由 Ping 或容量推算。</div>`+
    panel('指标覆盖',details([['容量、索引、记录数','已通过只读命令采集'],['数据库连接数 / 配额','未接入 Atlas 管理 API'],['每秒操作量','未接入 Atlas 管理 API'],['滚动七天传输量','未接入 Atlas 管理 API']]));}
function r2Page(){const m=state.modules.r2,inv=state.inventory;return moduleNote('r2')+`<div class="subtle-note">自动刷新只检查存储桶能否访问，不遍历所有对象。点击容量盘点后仅列举对象的大小和数量，不下载正文；每桶最多 200 次列表请求，可随时取消。列表盘点不是事务快照。</div><div class="equal-columns">${['chapters','covers'].map(id=>{const b=m.data?.buckets.find(x=>x.id===id),scan=inv.buckets.find(x=>x.id===id);return `<section class="panel bucket-panel"><div class="panel-head"><div><h2>${id==='chapters'?'正文、草稿与备份':'书籍封面'}</h2><div class="caption">${esc(b?.bucket||'等待连接')}</div></div>${b?tag(b.status==='ok'?'可访问':b.status==='unconfigured'?'未配置':'读取失败',b.status==='ok'?'ok':'warn'):tag('等待采集')}</div><div class="big-number">${scan?esc(bytes(scan.bytes)):'—'}</div><div class="small-copy">${scan?`${scan.complete?'盘点完成':'部分统计'} · ${number(scan.objects)} 个对象 · ${number(scan.pages)} 次列表请求`:'尚未盘点容量'}</div>${details([['桶响应耗时',b?.latencyMs?number(b.latencyMs)+' ms':'—'],['最近状态检查',time(m.lastSuccess)],['盘点完成时间',scan?.complete?time(scan.finishedAt):'—'],['容量统计口径','对象字节大小之和']])}${scan?.groups?`<div class="table-wrap"><table class="table"><thead><tr><th>用途</th><th>大小</th><th>对象数</th></tr></thead><tbody>${Object.entries(scan.groups).map(([name,g])=>`<tr><td>${esc(({chapters:'正文',drafts:'草稿',backups:'数据库备份',covers:'封面',other:'其他'})[name]||name)}</td><td>${bytes(g.bytes)}</td><td>${number(g.objects)}</td></tr>`).join('')}</tbody></table></div>`:''}</section>`;}).join('')}</div>`+
    panel('按需容量盘点',`<p class="small-copy">完整结果仅保留在本次内存中，需要留存可保存 JSON 报告。盘点期间若有对象新增或删除，结果可能随之变化。中断或达到上限时明确保留“部分统计”标记。</p><div class="actions"><button class="btn btn-primary" id="inventory-start" ${inv.running?'disabled':''}>${inv.running?'正在盘点…':'开始容量盘点'}</button>${inv.running?'<button class="btn btn-outline-secondary" id="inventory-cancel">取消盘点</button>':''}${refreshButton('r2')}</div>${inv.error?`<p class="small-copy status-error mt-3">${esc(inv.error)}</p>`:''}`)+
    panel('费用与请求量','<p class="small-copy mb-0">当前未接入 Cloudflare Analytics，只读 S3 凭据不能返回账号账单和历史请求量。这里保持“未接入”；容量盘点不会被当作官方账单数据。</p>');}
function reportPage(){const s=state.storage;return `<div class="metric-grid">${metric('已保存报告',`${s.files.length} 份`,'仅手动保存后生成')}${metric('报告占用',bytes(s.bytes),'专用目录预算 200 MiB')}${metric('默认保留期','30 天','超过期限的托管报告自动清理')}${metric('单份报告上限','16 MiB','防止意外生成超大文件')}</div>`+
    panel('本地文件',`<div class="report-path">${esc(s.directory)}</div><div class="actions mb-3"><button class="btn btn-primary" data-open-export>保存本次报告</button><button class="btn btn-outline-secondary" id="cleanup-plan">预览过期清理</button></div>${s.files.length?`<div class="table-wrap"><table class="table"><thead><tr><th>文件</th><th>保存时间</th><th>大小</th><th></th></tr></thead><tbody>${s.files.map(f=>`<tr><td class="text-mono">${esc(f.name)}</td><td>${date(f.mtime)}</td><td>${bytes(f.bytes)}</td><td><button class="btn btn-outline-secondary" data-download="${esc(f.name)}">下载副本</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">还没有保存报告<br>当前状态和曲线只保存在内存中。</div>'}`)+
    panel('清理规则',details([['触发时机','启动、运行每小时、保存前、退出'],['托管报告','超过 30 天，或超过 200 MiB 时先清理最旧报告'],['浏览器临时文件','窗口退出后清理；崩溃残留超过 1 天回收'],['外部副本','不进入自动清理范围'],['保留标记','.storage-keep 可保护目录'],['清理范围','仅本程序专用文件，不清理服务器、小说或备份']]))+
    '<div class="subtle-note">长期需要的报告请下载副本到其他目录。已保护的文件无法清理时，新报告会停止保存并提示，不会绕过保护。</div>';}
function settingsPage(){const c=state.config;return `<section class="panel"><div class="panel-head"><h2>服务器连接</h2>${tag('凭据留在服务器')}</div><form id="settings-form" class="settings-form"><div class="mb-4"><label class="form-label" for="host">SSH 主机</label><input class="form-control" id="host" name="host" value="${esc(c.host)}" required><div class="form-text">使用现有 SSH 密钥和已核验的 known_hosts，不自动接受新的主机指纹。</div></div><div class="mb-4"><label class="form-label" for="identity">本机 SSH 密钥路径</label><input class="form-control" id="identity" name="identity" value="${esc(c.identity)}" required><div class="form-text">只保存路径，不读取或导出密钥内容。</div></div><div class="mb-4"><label class="form-label" for="site">网站地址</label><input class="form-control" id="site" name="site" value="${esc(c.site)}" required></div><div class="mb-4"><label class="form-label" for="atlasLimitMiB">Atlas 套餐容量上限（MiB）</label><input class="form-control" id="atlasLimitMiB" name="atlasLimitMiB" type="number" min="1" max="100000000" placeholder="未填写，不推测套餐上限" value="${c.atlasLimitMiB??''}"><div class="form-text">以控制台的当前套餐为准。修改连接后会重新开始本次曲线，请先保存需要的报告。</div></div><button class="btn btn-primary" type="submit">保存并重新检测</button></form></section><div class="subtle-note">复用服务器现有连接配置执行固定只读查询。现有 SSH / 业务凭据本身可能拥有更高权限，本程序不创建新账号，也不修改服务器权限。程序内没有数据库写入、服务器清理或远程命令输入功能。</div>`;}
function render(force=false){if(!state)return;const sig=JSON.stringify([page,state.paused,Object.values(state.modules).map(m=>[m.lastAttempt,m.lastSuccess,m.status,m.stale,m.busy]),state.inventory,state.storage.files]);if(!force&&sig===signature)return;if(!force&&page==='settings')return;signature=sig;$('#content').innerHTML=({overview,server:serverPage,atlas:atlasPage,r2:r2Page,reports:reportPage,settings:settingsPage})[page]();}
function clocks(){if(!state)return;const secs=Math.floor((Date.now()-state.startedAt)/1000);$('#session-clock').textContent=`本次运行 ${String(Math.floor(secs/3600)).padStart(2,'0')}:${String(Math.floor(secs/60)%60).padStart(2,'0')}:${String(secs%60).padStart(2,'0')}`;const busy=Object.values(state.modules).some(x=>x.busy);$('#refresh').textContent=busy?'正在检测…':'刷新全部';$('#refresh').disabled=busy;$('#pause').textContent=state.paused?'继续刷新':'暂停刷新';$('#next-refresh').textContent=state.paused?'自动刷新已暂停':busy?'正在采集最新状态':`服务器将在 ${Math.max(0,Math.ceil((state.modules.server.nextDue-Date.now())/1000))} 秒后刷新`;}
async function poll(){if(polling)return;polling=true;try{state=await api('state');$('.site-address').firstChild.textContent=new URL(state.config.site).hostname+' ';$('#connection-banner').hidden=true;render();clocks();}catch(error){$('#connection-banner').hidden=false;$('#connection-banner').textContent='本地监控连接已中断，屏幕数据不再更新。'+error.message;}finally{polling=false;}}
async function act(fn){try{await fn();await poll();}catch(error){toast(error.message);}}
document.addEventListener('click',event=>{
  const button=event.target.closest('button');if(!button)return;
  if(button.dataset.page){page=button.dataset.page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x===button));$('#page-title').textContent=labels[page][0];$('#page-description').textContent=labels[page][1];render(true);return;}
  if(button.id==='save'||button.hasAttribute('data-open-export')){$('#export-dialog').showModal();return;}
  void act(async()=>{
    if(button.id==='refresh'||button.dataset.refresh){await api('refresh',button.dataset.refresh?{module:button.dataset.refresh}:{});return;}
    if(button.id==='pause'){await api('pause',{paused:!state.paused});return;}
    if(button.dataset.export){button.disabled=true;try{const result=await api('export',{format:button.dataset.export});$('#export-dialog').close();toast('已保存 '+result.name);}finally{button.disabled=false;}return;}
    if(button.id==='inventory-start'){await api('inventory',{});return;}
    if(button.id==='inventory-cancel'){await api('inventory/cancel',{});return;}
    if(button.id==='cleanup-plan'){const result=await api('cleanup',{});$('#cleanup-preview').innerHTML=`<p class="small-copy">可清理 ${result.candidates.length} 项，共 ${bytes(result.bytes)}。执行前会重新核对文件与保护条件。</p>${result.candidates.length?`<ul class="small-copy">${result.candidates.map(x=>`<li>${esc(x.path)} · ${bytes(x.bytes)}</li>`).join('')}</ul>`:'<p class="small-copy">当前没有需要清理的过期文件。</p>'}${result.protectedPaths.length?`<p class="small-copy">${result.protectedPaths.length} 项因保护规则保留。</p>`:''}`;$('#apply-cleanup').disabled=!result.candidates.length;$('#cleanup-dialog').showModal();return;}
    if(button.id==='apply-cleanup'){const result=await api('cleanup',{apply:true});$('#cleanup-dialog').close();toast(`已清理 ${result.deleted.length} 项，释放 ${bytes(result.bytes)}${result.skipped.length?'；部分文件已保留':''}`);return;}
    if(button.dataset.download){const res=await fetch('/api/report?name='+encodeURIComponent(button.dataset.download),{headers:{'x-monitor-token':token}});if(!res.ok)throw Error('无法读取报告');const url=URL.createObjectURL(await res.blob()),a=document.createElement('a');a.href=url;a.download=button.dataset.download;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
  });
});
document.addEventListener('submit',event=>{if(event.target.id!=='settings-form')return;event.preventDefault();const values=Object.fromEntries(new FormData(event.target));void act(async()=>{await api('config',values);toast('配置已保存，正在重新检测');});});
await poll();setInterval(poll,2000);setInterval(clocks,1000);
