import {assessHealth,capacityTone,percentage,growth,sourceState,serviceNames,isNumber as finite} from './health.mjs';
import {calendarPeriods,trendCounts} from './periods.mjs';
import {mountTrend} from './trend-chart.js';

const token=location.hash.slice(1)||sessionStorage.getItem('monitor-token')||'';if(token)sessionStorage.setItem('monitor-token',token);history.replaceState(null,'',location.pathname);
const $=s=>document.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=x=>finite(x)?x.toLocaleString('zh-CN',{maximumFractionDigits:1}):'—';
function bytes(x){if(!finite(x))return '—';if(x===0)return '0 B';const units=['B','KiB','MiB','GiB','TiB'],i=Math.min(4,Math.max(0,Math.floor(Math.log(Math.max(1,x))/Math.log(1024))));return `${(x/1024**i).toLocaleString('zh-CN',{maximumFractionDigits:i?1:0})} ${units[i]}`;}
const time=x=>x?new Date(x).toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}):'尚未取得';
const date=x=>x?new Date(x).toLocaleString('zh-CN',{hour12:false}):'尚未取得';
const pct=x=>finite(x)?`${x.toFixed(1)}%`:'—';
const tag=(label,tone='unknown')=>`<span class="tag ${tone}">${esc(label)}</span>`;
const jump=(target,text)=>`<button class="text-button" data-page="${target}">${esc(text)}</button>`;
const panel=(title,body,caption='',aside='')=>`<section class="panel"><div class="panel-head"><div><h2>${esc(title)}</h2>${caption?`<p class="caption">${esc(caption)}</p>`:''}</div>${aside}</div>${body}</section>`;
const detail=rows=>`<div class="detail-list">${rows.map(([k,v])=>`<div class="detail-item"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`;
const section=(title,aside='')=>`<div class="section-heading"><h2>${esc(title)}</h2><span>${aside}</span></div>`;
const tones={good:'余量充足',warning:'接近上限',danger:'余量紧张',unknown:'尚不明确'};
let state,page='overview',signature='',polling=false,toastTimer,rangeBusy=false;
let trendUnit='day',trendSource='visitors',disposeTrend=()=>{};
const labels={overview:['运行概况','读者变化一眼看清，运行异常及时呈现。'],audience:['访问来源与热门内容','看看读者从哪里来，喜欢读什么。'],resources:['还有多少余量','容量接近上限时提前处理，服务异常时及时定位。'],storage:['小说和封面是否可用','先确认读者能看到内容，再按需查看存储占用。'],reports:['留下记录，轻装运行','需要时保存一份报告，过期的本地文件可以安全清理。'],settings:['把数据连接起来','连接一次，之后直接在这里看懂网站。']};
async function api(route,data){const res=await fetch('/api/'+route,{method:data===undefined?'GET':'POST',headers:{'x-monitor-token':token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw Error(result.error||'请求失败');return result;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6500);}
const connected=key=>state.modules[key]?.data?.status==='connected';
function sourceNote(key){const m=state.modules[key];if(!m)return '';if(m.status==='error'||m.stale)return `<div class="notice warning">${esc(m.error||'这组数据已过期，请刷新。')}${m.data?' 当前保留上次成功结果，不能当作最新数据。':''}</div>`;return m.data?.notice?`<p class="data-caption">${esc(m.data.notice)}</p>`:'';}
function stamp(key){const m=state.modules[key];return `上次成功 ${time(m?.lastSuccess)}${m?.status==='error'||m?.stale?' · 旧数据':''}`;}
function refresh(key){return `<button class="btn small" data-refresh="${key}" ${state.modules[key]?.busy?'disabled':''}>${state.modules[key]?.busy?'检测中…':'重新检测'}</button>`;}
function meter(label,ratio,tone){return `<div class="meter ${tone}" role="meter" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="100" ${finite(ratio)?`aria-valuenow="${Math.min(100,Math.max(0,ratio))}"`:''} aria-valuetext="${finite(ratio)?esc(pct(ratio)):'容量上限未知'}"><div class="meter-fill" style="width:${finite(ratio)?Math.min(100,Math.max(0,ratio)):0}%"></div></div>`;}
function resourceCard(r){const available=finite(r.total)&&finite(r.used)?r.total-r.used:null;return `<article class="resource-card compact-resource"><div class="resource-top"><h3>${esc(r.label)}</h3>${tag(r.tone==='good'?pct(r.ratio)+' 已用':tones[r.tone],r.tone)}</div>${meter(r.label,r.ratio,r.tone)}<p class="capacity-caption">${finite(available)?`${esc(bytes(Math.max(0,available)))} 可用，共 ${esc(bytes(r.total))}`:`${esc(bytes(r.used))} 已用 · 上限未确认`}${!r.fresh?' · 旧值/待检测':''}${r.id==='atlas'&&!r.total?' '+jump('settings','设置'):''}</p></article>`;}
function metric(label,value,unit,description,comparison){const delta=comparison?growth(comparison[0],comparison[1]):null;return `<article class="metric-card"><div class="metric-label">${esc(label)}</div><div class="metric-value">${esc(value)}<small>${esc(unit)}</small></div>${delta?`<div class="growth ${delta.direction}">${esc(delta.text)}${['up','down'].includes(delta.direction)?' · 对比前一等长周期':''}</div>`:''}<div class="metric-detail">${esc(description)}</div></article>`;}
function issuesList(health,limit=50){if(!health.issues.length)return '<div class="success-note"><strong>✓ 暂时没有需要处理的事项</strong><p>已检查的项目正常。容量达到 80% 会提醒，达到 90% 会标红。</p></div>';return `<div class="issue-list">${health.issues.slice(0,limit).map(i=>`<div class="issue ${i.level}"><span class="issue-dot" aria-hidden="true"></span><div class="issue-copy"><strong>${esc(i.title)}</strong><p>${esc(i.detail)}</p></div>${i.target!=='overview'?jump(i.target,'查看'):''}</div>`).join('')}</div>${health.issues.length>limit?`<p class="readable-note">另有 ${health.issues.length-limit} 项，${jump('resources','查看全部检测结果')}</p>`:''}`;}
function statusStrip(health){return `<section class="status-strip ${health.level}" aria-label="网站状态"><div class="status-summary"><span class="status-dot ${health.level}" aria-hidden="true"></span><h2>${esc(health.title)}</h2><span class="caption">${health.checks.filter(c=>c.level==='good').length}/4 项访问检查通过 · ${stamp('site')}</span>${jump('resources','服务详情')}</div>${health.issues.length?issuesList(health,3):''}<details data-detail="访问抽查"><summary>查看访问抽查</summary><div class="check-grid">${health.checks.map(c=>`<div class="check-item ${c.level}"><span class="check-icon">${c.level==='good'?'✓':c.level==='danger'?'!':'·'}</span><div>${esc(c.label)}<small>${c.level==='good'?'访问正常':c.level==='danger'?'需要检查':'尚未确认'}${finite(c.latencyMs)?' · '+number(c.latencyMs)+' ms':''}</small></div></div>`).join('')}</div><p class="caption">正文为单本书抽查；关闭窗口后停止本机检测。</p></details></section>`;}
function trendData(){
  if(trendSource==='visitors')return {points:state.modules.analytics?.data?.activity?.trends?.[trendUnit]||[],series:[{key:'activeUsers',label:'活跃用户',color:'#287d64'},{key:'newUsers',label:'新增访客',color:'#c68b36'}]};
  const b=state.modules.business?.data;
  return {points:b?.registrationHistory?calendarPeriods(b.todayDate,trendUnit,trendCounts[trendUnit]).map(p=>({...p,newUsers:b.registrationHistory.filter(r=>r.date>=p.date&&r.date<=p.endDate).reduce((n,r)=>n+r.newUsers,0)})):[],series:[{key:'newUsers',label:'新增注册',color:'#587ea6'}]};
}
function overview(){const health=assessHealth(state),b=state.modules.business?.data,g=connected('analytics')?state.modules.analytics.data:null,rt=connected('realtime')?state.modules.realtime.data:null,a=g?.activity;
  const status=statusStrip(health),attention=health.level==='danger'||health.level==='warning';
  const unitLabel={day:'90 个完整自然日',week:'26 个完整自然周（周一至周日）',month:'12 个完整自然月'}[trendUnit];
  const controls=`<div class="trend-selectors"><div class="segmented" role="group" aria-label="用户数据类型">${[['visitors','访问用户'],['registrations','新增注册']].map(([key,label])=>`<button data-trend-source="${key}" aria-pressed="${trendSource===key}" class="${trendSource===key?'active':''}">${label}</button>`).join('')}</div><div class="segmented" role="group" aria-label="趋势时间单位">${[['day','日'],['week','周'],['month','月']].map(([key,label])=>`<button data-trend-unit="${key}" aria-pressed="${trendUnit===key}" class="${trendUnit===key?'active':''}">${label}</button>`).join('')}</div></div>`;
  return (attention?status:'')+sourceNote('analytics')+`<div class="metric-grid activity-metrics">${metric('日活 DAU',number(a?.rolling?.[1]?.activeUsers),'人','昨日去重活跃用户')}${metric('周活 WAU',number(a?.rolling?.[7]?.activeUsers),'人','截至昨日，最近 7 天去重')}${metric('月活 MAU',number(a?.rolling?.[30]?.activeUsers),'人','截至昨日，最近 30 天去重')}${metric('昨日新增访客',number(a?.rolling?.[1]?.newUsers),'人',`近 7 天 ${number(a?.rolling?.[7]?.newUsers)} · 近 30 天 ${number(a?.rolling?.[30]?.newUsers)} 人`)}</div>`+
    (!g?analyticsEmpty():`<p class="data-caption">截至 ${esc(a?.endDate||g.endDate)} · 谷歌时区 ${esc(g.timeZone)} · ${stamp('analytics')} · 未额外剔除疑似自动化访问${g.notices?.length?' · '+esc(g.notices.join('；')):''}</p>`)+
    panel('用户变化',`<p class="caption trend-hint">最近 ${unitLabel} · ${trendSource==='visitors'?`谷歌时区 ${esc(g?.timeZone||'待连接')} · 每个周期单独去重`:'北京时间 · 按现存账号注册日期统计'}。悬停或轻触查看数据，滚轮缩放。</p><div id="user-trend"></div>`,'',controls)+
    `<div class="reader-strip"><div><span>今天活跃</span><strong>${number(g?.today?.activeUsers)}</strong></div><div><span>近 30 分钟活跃</span><strong>${number(rt?.activeUsers)}</strong></div><div><span>今天新增访客</span><strong>${number(g?.today?.newUsers)}</strong></div><div><span>今天浏览次数</span><strong>${number(g?.today?.screenPageViews)}</strong></div><div><span>今天新增注册</span><strong>${number(b?.todayNewUsers)}</strong></div><div><span>现有注册账号</span><strong>${number(b?.totalUsers)}</strong></div></div><p class="data-caption">今天尚未结束，数据会继续更新；访客不等于注册账号，注册按北京时间统计。${b?.unknownRegistrationDates?`${number(b.unknownRegistrationDates)} 个账号注册日期无效，未计入趋势。`:''}</p>${sourceNote('realtime')}${sourceNote('business')}`+
    `<div class="capacity-heading"><h2>容量</h2><span>已用 80% 提醒 · 90% 标红</span>${jump('resources','查看详情')}</div><div class="resource-grid">${health.resources.map(resourceCard).join('')}</div>`+(attention?'':status);
}

function chart(points,series,{title='趋势',daily=true,max:fixedMax,unit='人'}={}) {
  if(!points?.length||!points.some(p=>series.some(s=>finite(p[s.key]))))return '<div class="chart-empty">尚无可用数据</div>';
  const data=points.slice(-180),w=680,h=240,left=42,right=14,top=18,bottom=32,values=data.flatMap(p=>series.map(s=>finite(p[s.key])?p[s.key]:0));
  const max=fixedMax||Math.max(4,Math.ceil(Math.max(...values)/4)*4),x=i=>left+i/Math.max(1,data.length-1)*(w-left-right),y=v=>top+(1-v/max)*(h-top-bottom),label=p=>daily?p.date?.slice(5):time(p.at);
  let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}"><title>${esc(title)}，单位：${esc(unit)}；下方可展开每日数字</title>`;
  for(let i=0;i<=4;i++){const value=max*i/4,Y=y(value);svg+=`<line x1="${left}" y1="${Y}" x2="${w-right}" y2="${Y}" stroke="#e8eeea" stroke-dasharray="3 5"/><text x="${left-9}" y="${Y+4}" text-anchor="end">${number(value)}</text>`;}
  for(const s of series){let move=true,d='';data.forEach((p,i)=>{if(!finite(p[s.key])||p.gap){move=true;return;}d+=`${move?'M':'L'}${x(i).toFixed(1)},${y(p[s.key]).toFixed(1)} `;move=false;});svg+=`<path d="${d}" stroke="${s.color}" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`;
    data.forEach((p,i)=>{if(!finite(p[s.key])||p.gap)return;svg+=`<circle cx="${x(i)}" cy="${y(p[s.key])}" r="${data.length>35?2:3.5}" fill="${s.color}"><title>${esc(label(p))} · ${esc(s.label)} ${number(p[s.key])} ${esc(unit)}</title></circle>`;});}
  for(const i of [...new Set([0,Math.floor((data.length-1)/2),data.length-1])])svg+=`<text x="${x(i)}" y="${h-5}" text-anchor="${i===0?'start':i===data.length-1?'end':'middle'}">${esc(label(data[i]))}</text>`;
  svg+='</svg>';
  return `<div class="legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${esc(s.label)}</span>`).join('')}<span>单位：${esc(unit)}</span></div>${svg}${daily?`<details class="chart-data" data-detail="${esc(title)}"><summary>查看每日数字</summary><div class="table-wrap"><table><thead><tr><th>日期</th>${series.map(s=>`<th>${esc(s.label)}</th>`).join('')}</tr></thead><tbody>${data.map(p=>`<tr><td>${esc(p.date)}</td>${series.map(s=>`<td>${number(p[s.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`:''}`;
}
function ranking(rows,{field='value',name='name',unit='次',subtitle}={}){if(!rows?.length)return '<div class="empty-small">这个范围内暂时没有记录</div>';const max=Math.max(1,...rows.map(r=>r[field]||0));return `<div class="rank-list">${rows.map((r,i)=>`<div class="rank-row"><span class="rank-index">${String(i+1).padStart(2,'0')}</span><div class="rank-copy"><span class="rank-name" title="${esc(r[name])}">${esc(r[name]||'未识别')}</span>${subtitle?`<span class="rank-subtitle" title="${esc(r[subtitle])}">${esc(r[subtitle])}</span>`:''}<div class="rank-bar" aria-hidden="true"><span style="width:${Math.max(0,Math.min(100,r[field]/max*100))}%"></span></div></div><span class="rank-value">${number(r[field])}<small>${esc(unit)}</small></span></div>`).join('')}</div>`;}
const channels={'Direct':'直接访问','Organic Search':'搜索引擎','Referral':'其他网站推荐','Organic Social':'社交平台','Unassigned':'来源未识别','Paid Search':'付费搜索','Email':'邮件','Organic Video':'视频平台','(not set)':'来源未提供'};
function deviceChart(rows){const colors=['#397b5b','#8eb29a','#c3d1b6','#9daab5'],names={mobile:'手机',desktop:'电脑',tablet:'平板','(not set)':'未识别'},total=rows.reduce((n,r)=>n+r.value,0);if(!total)return '<div class="empty-small">暂时没有设备数据</div>';let position=0;const slices=rows.map((r,i)=>{const start=position;position+=r.value/total*100;return `${colors[i%colors.length]} ${start}% ${position}%`;});return `<div class="donut-layout"><div class="donut" style="background:conic-gradient(${slices.join(',')})" role="img" aria-label="按访问次数划分的设备占比"><div class="donut-center"><strong>${number(total)}</strong><small>次访问</small></div></div><div class="donut-legend">${rows.map((r,i)=>`<div class="donut-row"><span><i style="background:${colors[i%colors.length]}"></i>${esc(names[r.name]||r.name)}</span><strong>${pct(r.value/total*100)} · ${number(r.value)}</strong></div>`).join('')}</div></div>`;}
function analyticsEmpty(){const m=state.modules.analytics;return `<section class="panel empty-state analytics-empty"><div class="empty-symbol" aria-hidden="true">↗</div><h3>${m?.status==='error'?'谷歌统计暂时没有读到':m?.busy?'正在读取谷歌统计':'连接谷歌，看见读者的变化'}</h3><p>${esc(m?.error||'完成一次只读授权后，这里会显示活跃访客、增长趋势、热门页面和访问来源。新增注册可在运行概况查看，阅读统计在访客与内容页查看。')}</p>${jump('settings','前往谷歌连接设置 →')}</section>`;}
function audience(){const b=state.modules.business?.data,g=connected('analytics')?state.modules.analytics.data:null,days=state.config.analyticsDays;
  let html=`<div class="range-strip"><div><strong>最近 ${days} 个完整自然日</strong><p>截至昨天；用户增长已移至运行概况。</p></div><div class="segmented" role="group" aria-label="统计时间范围">${[7,30,90].map(d=>`<button data-range="${d}" aria-pressed="${days===d}" class="${days===d?'active':''}" ${rangeBusy?'disabled':''}>${d} 天</button>`).join('')}</div></div>`+sourceNote('analytics');
  if(g)html+=`<div class="content-counts"><span>本期页面浏览 <strong>${number(g.current.screenPageViews)}</strong> 次</span><span>本期访问 <strong>${number(g.current.sessions)}</strong> 次</span></div><div class="equal-columns">${panel('他们从哪里来',ranking(g.channels.map(r=>({...r,name:channels[r.name]||r.name}))), '按访问次数统计，同一访客可以多次访问。')}${panel('读者使用的设备',deviceChart(g.devices),'按谷歌返回的访问次数划分。')}</div>`+
    panel('哪些页面最受欢迎',ranking(g.pages.map(r=>({...r,title:(r.title||r.path).replace(/\s*[-–_]\s*九天小说站.*$/,'')})),{field:'views',name:'title',subtitle:'path'}),'浏览次数最多的 10 个页面记录；页面改名可能分行。')+
    `<p class="data-caption">${esc(g.startDate)} 至 ${esc(g.endDate)} · 谷歌时区 ${esc(g.timeZone)} · ${stamp('analytics')}${g.notices?.length?' · '+esc(g.notices.join('；')):''}</p>`;
  else html+=analyticsEmpty();
  html+=sourceNote('business');
  if(!b)return html+panel('正在读取阅读统计','<div class="empty-small">'+esc(state.modules.business?.error||'首次读取完成后显示；未取得的数据不会显示成 0。')+'</div>');
  return html+panel('实际阅读的变化',chart(b.daily,[{key:'reads',label:'章节阅读',color:'#537b9f'}],{title:'每日有效章节阅读',unit:'次'}),`所选周期 ${number(b.current.reads)} 次。已剔除展示基数；同一身份同一天重复读同一章只计一次。`)+
    `<div class="equal-columns">${panel('读者最近在看什么',ranking(b.topBooks,{field:'views',name:'title'}),`所选 ${b.days} 天内的有效章节阅读，仅公开作品。`)}${panel('哪些书被加入书架',ranking(b.bookmarks,{field:'count',name:'title',unit:'份收藏'}),'当前仍保留的收藏总量，不受上方日期范围影响。')}</div>`+
    `<p class="readable-note">${stamp('business')} · 北京时间。阅读次数不等于阅读人数。</p>`;
}

function resources(){const health=assessHealth(state),s=state.modules.server.data,a=state.modules.atlas.data,fresh=sourceState(state.modules.server)==='good';
  const serviceRows=(s?.services||[]).filter(x=>serviceNames[x.Id]).map(x=>{const max=Number(x.MemoryMax),used=Number(x.MemoryCurrent),ratio=max>0&&max<1e15&&used>=0&&used<1e15?percentage(used,max):null,tone=fresh?(x.ActiveState==='active'?'good':'danger'):'unknown';return `<div class="service-row"><div><strong>${esc(serviceNames[x.Id])}</strong><p>${x.Id.endsWith('.timer')?'定时维护任务':'直接影响读者访问'}${Number(x.NRestarts)>0?' · 记录到 '+number(Number(x.NRestarts))+' 次自动重启':''}</p></div>${finite(ratio)?`<div class="service-memory">${meter(serviceNames[x.Id]+'内存',ratio,fresh?capacityTone(ratio):'unknown')}<div class="meter-meta"><span>进程内存 ${pct(ratio)}</span><span>${bytes(used)} / ${bytes(max)}</span></div></div>`:''}${tag(tone==='good'?'运行中':tone==='danger'?'未正常运行':'尚未确认',tone)}</div>`;}).join('');
  return sourceNote('server')+sourceNote('atlas')+`<div class="resource-grid">${health.resources.map(resourceCard).join('')}</div>`+
    `<div class="equal-columns">${panel('风险与检查结果',issuesList(health), '缺少检测结果和实际故障会分别标注。')}${panel('关键服务',serviceRows||'<div class="empty-small">等待服务状态</div>','服务器有空闲内存时，单个服务也可能达到自身限制。',refresh('server'))}</div>`+
    `<div class="equal-columns">${panel('运行压力有没有持续升高',chart(state.modules.server.history,[{key:'cpu',label:'处理器',color:'#347e5a'},{key:'memory',label:'运行内存',color:'#7194b4'}],{title:'服务器运行压力',daily:false,max:100,unit:'%'}),'本次打开期间的采样；短暂高峰不等于故障。')}${panel('发生问题后能否恢复',detail([['最近备份',date(s?.backup?.finishedAt||s?.backup?.createdAt)],['备份结果',s?.backup?(['success','ok','completed'].includes(s.backup.status)?'已报告成功':'需检查'):'尚未取得'],['服务器运行',s?number(Math.floor(s.uptime/86400))+' 天':'—'],['首页响应',state.modules.site.data?number(state.modules.site.data.latencyMs)+' ms':'—']]),'成功备份超过 36 小时未更新时提醒；未在这里执行恢复演练。')}</div>`+
    panel('数据库',detail([['连接检查',sourceState(state.modules.atlas)==='good'?'正常':'尚未确认'],['连接响应',finite(a?.pingMs)?number(a.pingMs)+' ms':'—'],['整个集群用量',bytes(a?.cluster?.logicalBytes)],['已配置套餐上限',state.config.atlasLimitMiB?number(state.config.atlasLimitMiB)+' MiB':'尚未设置']]),'容量用整个集群的数据与索引衡量；上限以你的实际套餐为准。',jump('settings','修改容量上限'))+
    `<details class="panel technical" data-detail="技术详情"><summary>需要排查时，展开技术详情</summary>${detail([['当前部署',s?.release||'—'],['处理器核心',number(s?.cores)],['当前处理器占用',pct(s?.cpuPercent)],['剩余文件名额',number(s?.disk?.freeInodes)],['交换空间已用',bytes(s?.memory?.swapUsed)],['数据库名称',a?.database||'—'],['业务库数据',bytes(a?.dataBytes)],['业务库索引',bytes(a?.indexBytes)],['数据库管理配额','未接入 Atlas 管理 API'],['备份可恢复性','需要定期恢复演练验证']])}<p class="readable-note">数据库连接数量和传输配额尚未接入，不能据此判断所有数据库风险。${stamp('server')}；${stamp('atlas')}。</p></details>`;
}
function storagePage(){const m=state.modules.r2,inv=state.inventory,fresh=sourceState(m)==='good';return sourceNote('r2')+`<div class="notice">小说正文和封面保存在云端，不占服务器磁盘。这里先检查能否访问；容量盘点是手动操作，不会下载正文。</div><div class="equal-columns">${['chapters','covers'].map(id=>{const b=m.data?.buckets.find(x=>x.id===id),scan=inv.buckets.find(x=>x.id===id),tone=fresh&&b?(b.status==='ok'?'good':b.status==='error'?'danger':'unknown'):'unknown';return panel(id==='chapters'?'小说正文、草稿与备份':'书籍封面',`<div class="big-number">${scan?bytes(scan.bytes):'—'}</div><p class="caption">${scan?`${scan.complete?'本次盘点完成':'已读取的部分容量'} · ${number(scan.objects)} 个对象`:'尚未盘点容量'}</p>${scan?ranking(Object.entries(scan.groups).map(([name,x])=>({name:({chapters:'正文',drafts:'草稿',backups:'备份',covers:'封面',other:'其他'})[name]||name,value:x.bytes})),{unit:'字节'}):''}<p class="readable-note">${id==='chapters'?'无法访问时可能影响小说阅读和恢复备份。':'无法访问时可能影响封面显示。'}${finite(b?.latencyMs)?' 响应 '+number(b.latencyMs)+' ms。':''}</p><details class="technical" data-detail="${id}"><summary>查看盘点详情</summary>${detail([['存储桶',b?.bucket||'—'],['列表请求',scan?number(scan.pages):'—'],['容量性质','对象列表汇总，非官方账单'],['最后检查',time(m.lastSuccess)]])}</details>`,'',tag(tone==='good'?'可访问':tone==='danger'?'检查失败':'尚未确认',tone));}).join('')}</div>`+panel('按需查看占用',`<div class="actions"><button class="btn primary" id="inventory-start" ${inv.running?'disabled':''}>${inv.running?'正在盘点…':'开始容量盘点'}</button>${inv.running?'<button class="btn" id="inventory-cancel">取消盘点</button>':''}${refresh('r2')}</div><p class="readable-note">最多每桶 200 次列表请求。中断或达到上限会标注“部分容量”，不能当作总量。</p>${inv.error?`<p class="notice warning">${esc(inv.error)}</p>`:''}`,'R2 没有在此配置容量硬上限，因此不画“即将装满”的容量条。')+`<p class="readable-note">Cloudflare 的历史请求量、免费额度和账单尚未接入。对象容量不能直接推算实际费用。</p>`;}

function reports(){return panel('保存可带走的检测记录',`<p class="caption">JSON 包含当前全部汇总数据；CSV 保存本次打开期间的服务器运行曲线。</p><div class="actions" style="margin-top:18px"><button class="btn primary" data-open-export>保存本次报告</button><button class="btn" id="cleanup-plan">预览过期清理</button></div><p class="readable-note">只清理本程序的过期报告和退出后的临时浏览器文件，小说、数据库和服务器不在清理范围内。</p>`)+panel('已经保存的报告',`<p class="report-path">${esc(state.storage.directory)}</p>${state.storage.files.length?`<div class="table-wrap"><table><thead><tr><th>保存时间</th><th>格式</th><th>大小</th><th>操作</th></tr></thead><tbody>${state.storage.files.map(f=>`<tr><td>${date(f.mtime)}</td><td>${esc(f.name.split('.').at(-1).toUpperCase())}</td><td>${bytes(f.bytes)}</td><td><button class="btn small" data-download="${esc(f.name)}">下载副本</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-small">还没有保存报告，运行数据目前仅在内存中。</div>'}`,`${state.storage.files.length} 份 · 共 ${bytes(state.storage.bytes)} · 保留 30 天，目录上限 200 MiB`);}
const field=(name,label,value,hint='',type='text')=>`<div class="field"><label for="${name}">${esc(label)}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value??'')}" autocomplete="off">${hint?`<p class="caption">${esc(hint)}</p>`:''}</div>`;
function settings(){const c=state.config;return `<div class="settings-layout">${panel('连接谷歌统计',`<form id="analytics-form">${field('gaPropertyId','谷歌资源 ID',c.gaPropertyId,'纯数字资源 ID；不是 G- 开头的衡量 ID。')}${field('gaCredentialsPath','本机授权文件路径',c.gaCredentialsPath,'已有只读授权 JSON 时填写完整路径，或通过下方按钮选择文件。')}<div class="file-upload"><label for="google-file">选择谷歌授权 JSON 文件</label><input id="google-file" type="file" accept=".json,application/json"><p class="caption">选择后点击“保存并检测”。授权仅保存在这台电脑，不上传到网站，也不写入报告。</p></div><button class="btn primary" type="submit">保存并检测谷歌连接</button><p class="form-status" id="ga-status">${connected('analytics')?'已成功读取谷歌报表':c.gaCredentialsPath?'已配置授权文件，检测结果见下方':'等待只读授权'}</p></form><div id="ga-connection-note">${sourceNote('analytics')}</div>`, '只读取报表，不修改谷歌统计或网站。')}${panel('首次连接怎么做',`<ol class="setup-steps"><li><strong>准备谷歌的只读授权</strong><br>在 Google Cloud 选择项目，启用 Google Analytics Data API，创建专用于监控的服务账号并下载 JSON 密钥文件。</li><li><strong>允许它查看网站报表</strong><br>在 Google Analytics 的“管理 → 媒体资源访问权限管理”中，将文件里的 client_email 添加为“查看者”。无需编辑或管理员权限。</li><li><strong>回到这里连接</strong><br>填写网站的数字资源 ID，选择刚才的 JSON 文件，点击“保存并检测”。之后打开监控即可自动读取。</li></ol><p class="readable-note">资源 ID 可以从谷歌页面地址中的 p 后数字找到。浏览器已经登录谷歌，也仍需要给本程序单独的报表读取授权。</p><p class="caption"><a href="https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart" target="_blank" rel="noreferrer">谷歌官方接入说明 ↗</a></p><p class="caption">也支持包含 analytics.readonly 权限的 Application Default Credentials。不要将授权文件发送到聊天或提交到代码仓库。</p>`)}</div>`+
    `<div style="margin-top:22px">${panel('服务器与容量',`<form id="settings-form">${field('atlasLimitMiB','数据库套餐容量上限（MiB）',c.atlasLimitMiB,'按实际 Atlas 套餐填写。未填写时会显示“容量余量尚不明确”，不猜测你的套餐。','number')}<details class="technical" data-detail="连接参数"><summary>查看或修改服务器连接参数</summary>${field('host','SSH 主机',c.host)}${field('identity','SSH 密钥路径',c.identity)}${field('site','网站地址',c.site)}</details><div class="actions" style="margin-top:20px"><button class="btn primary" type="submit">保存服务器设置</button></div></form>`,'默认沿用已有连接。网站监控读取数据，不写入业务数据库。')}</div>`;}

function navigate(target){if(!labels[target])return;page=target;signature='';document.querySelectorAll('.nav-item[data-page]').forEach(x=>{x.classList.toggle('active',x.dataset.page===page);if(x.dataset.page===page)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});$('#page-title').textContent=labels[page][0];$('#page-description').textContent=labels[page][1];render(true);window.scrollTo(0,0);}
function render(force=false){if(!state)return;if(page==='settings'&&!force){$('#ga-connection-note').innerHTML=sourceNote('analytics');$('#ga-status').textContent=state.modules.analytics?.busy?'正在读取谷歌报表…':state.modules.analytics?.status==='error'?'连接尚未成功，请查看下方提示':connected('analytics')?'已成功读取谷歌报表 · '+stamp('analytics'):state.config.gaCredentialsPath?'已配置授权文件':'等待只读授权';return;}const next=JSON.stringify([page,state.modules,state.inventory,state.storage,state.config.analyticsDays,rangeBusy]);if(!force&&signature===next)return;signature=next;const open=new Set([...document.querySelectorAll('details[open][data-detail]')].map(e=>e.dataset.detail));const focused=document.activeElement?.dataset;const focusKey=focused?.trendUnit?['trend-unit',focused.trendUnit]:focused?.trendSource?['trend-source',focused.trendSource]:focused?.range?['range',focused.range]:focused?.refresh?['refresh',focused.refresh]:focused?.control?['control',focused.control]:null;disposeTrend();$('#content').innerHTML=({overview,audience,resources,storage:storagePage,reports,settings})[page]();if(page==='overview'){const data=trendData();disposeTrend=mountTrend($('#user-trend'),data.points,data.series,trendSource+':'+trendUnit);}document.querySelectorAll('details[data-detail]').forEach(e=>{if(open.has(e.dataset.detail))e.open=true;});if(focusKey)$(`[data-${focusKey[0]}="${focusKey[1]}"]`)?.focus({preventScroll:true});}
function clocks(){if(!state)return;$('#session-clock').textContent='本机时间 '+time(Date.now());const busy=Object.values(state.modules).some(x=>x.busy);$('#refresh').textContent=busy?'正在检测…':'立即检测';$('#refresh').disabled=busy;$('#pause').textContent=state.paused?'继续刷新':'暂停刷新';$('#next-refresh').textContent=state.paused?'自动刷新已暂停':busy?'正在读取最新结果':`运行状态 ${Math.max(0,Math.ceil((state.modules.server.nextDue-Date.now())/1000))} 秒后刷新`;}
async function poll(){if(polling)return;polling=true;try{state=await api('state');$('.site-address').textContent=new URL(state.config.site).hostname;$('#connection-banner').hidden=true;render();clocks();}catch(error){$('#connection-banner').hidden=false;$('#connection-banner').textContent='监控连接已中断，下方是旧结果，不能确认网站当前状态。'+error.message;}finally{polling=false;}}
async function act(fn){try{await fn();await poll();}catch(error){toast(error.message);}}
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.page){navigate(button.dataset.page);return;}if(button.dataset.trendUnit){trendUnit=button.dataset.trendUnit;render(true);return;}if(button.dataset.trendSource){trendSource=button.dataset.trendSource;render(true);return;}if(button.closest('#user-trend'))return;if(button.hasAttribute('data-open-export')){$('#export-dialog').showModal();return;}void act(async()=>{
  if(button.id==='refresh'||button.dataset.refresh){await api('refresh',button.dataset.refresh?{module:button.dataset.refresh}:{});return;}
  if(button.id==='pause'){await api('pause',{paused:!state.paused});return;}
  if(button.dataset.range){if(rangeBusy)return;rangeBusy=true;render(true);try{await api('range',{days:Number(button.dataset.range)});}finally{rangeBusy=false;signature='';}return;}
  if(button.dataset.export){button.disabled=true;try{const result=await api('export',{format:button.dataset.export});$('#export-dialog').close();toast('已保存 '+result.name);}finally{button.disabled=false;}return;}
  if(button.id==='inventory-start'){await api('inventory',{});return;}if(button.id==='inventory-cancel'){await api('inventory/cancel',{});return;}
  if(button.id==='cleanup-plan'){const result=await api('cleanup',{});$('#cleanup-preview').innerHTML=`<p class="caption">可清理 ${result.candidates.length} 项，共 ${bytes(result.bytes)}。执行前会再次核对保护规则。</p>${result.candidates.length?`<ul class="caption">${result.candidates.map(x=>`<li>${esc(x.path)} · ${bytes(x.bytes)}</li>`).join('')}</ul>`:'<p class="caption">当前没有需要清理的过期文件。</p>'}`;$('#apply-cleanup').disabled=!result.candidates.length;$('#cleanup-dialog').showModal();return;}
  if(button.id==='apply-cleanup'){const result=await api('cleanup',{apply:true});$('#cleanup-dialog').close();toast(`已清理 ${result.deleted.length} 项，释放 ${bytes(result.bytes)}`);return;}
  if(button.dataset.download){const res=await fetch('/api/report?name='+encodeURIComponent(button.dataset.download),{headers:{'x-monitor-token':token}});if(!res.ok)throw Error('无法读取报告');const url=URL.createObjectURL(await res.blob()),a=document.createElement('a');a.href=url;a.download=button.dataset.download;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
});});
document.addEventListener('submit',event=>{const form=event.target;if(!['settings-form','analytics-form'].includes(form.id))return;event.preventDefault();const values=Object.fromEntries(new FormData(form)),button=form.querySelector('button[type="submit"]');void act(async()=>{button.disabled=true;try{if(form.id==='analytics-form'&&$('#google-file').files[0]){const file=$('#google-file').files[0];if(file.size>16384)throw Error('授权文件超过 16 KiB，请确认选择的是谷歌授权 JSON');let credentials;try{credentials=JSON.parse(await file.text());}catch{throw Error('所选文件不是有效 JSON');}await api('analytics/credentials',{propertyId:values.gaPropertyId,credentials});}else await api('config',values);toast('设置已保存，正在核对连接结果');await poll();render(true);}finally{button.disabled=false;}});});
await poll();setInterval(poll,2000);setInterval(clocks,1000);
