import {test,expect,type Page} from '@playwright/test';
const base=process.env.MANUSCRIPT_BASE_URL || 'http://127.0.0.1:3107';
test.beforeEach(async({page})=>{
  const csrf=await(await page.request.get(base+'/api/auth/csrf')).json();
  const login=await page.request.post(base+'/api/auth/signin',{headers:{origin:base,'x-csrf-token':csrf.csrfToken},data:{email:'manuscript@example.test',password:'Manuscript-test-123'}});
  expect(login.ok()).toBe(true);
});
async function create(page:Page,title:string) {
  await page.goto(base+'/writer?action=new');
  await page.getByLabel('书名',{exact:true}).fill(title);
  await page.getByLabel('简介',{exact:true}).fill('故事的第一段简介。');
  await page.getByRole('button',{name:'创建',exact:true}).click();
  await expect(page).toHaveURL(base+'/writer');
  return page.locator('.writer-work').filter({hasText:title});
}
for(const width of [320,1440]) test(`metadata editing preserves draft chapters and published status at ${width}`,async({page},info)=>{
  await page.setViewportSize({width,height:844});
  const title='资料'+width+Date.now().toString().slice(-5), edited=title+'新';
  let card=await create(page,title);
  await card.getByRole('button',{name:'创作',exact:true}).click();
  await expect(page.locator('.manuscript-work-title')).toHaveText(title);
  await expect(page.getByLabel('书名',{exact:true})).toHaveCount(0);
  await expect(page.getByLabel('简介',{exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'直接码字',exact:true}).click();
  await page.getByLabel('在线章节正文').fill('第一卷 风起\n第一章 来信\n不能丢失的第一章正文。\n第二章 远行\n不能丢失的第二章正文。');
  await page.getByRole('button',{name:'预览章节',exact:true}).click();
  await page.getByRole('button',{name:'保存草稿',exact:true}).click();
  const works=await(await page.request.get(base+'/api/writer/works?limit=20')).json();
  const key=works.find((work:{title:string})=>work.title===title).manuscriptKey;
  const before=await(await page.request.get(base+'/api/manuscripts/'+key)).json();
  await card.getByLabel(`管理《${title}》`).click();
  await card.getByRole('button',{name:'编辑作品',exact:true}).click();
  const editor=page.getByRole('dialog',{name:'编辑作品',exact:true});
  await expect(editor.locator('form')).toHaveAttribute('data-busy','false');
  await editor.getByLabel('书名',{exact:true}).fill(edited);
  await editor.getByLabel('简介',{exact:true}).fill('在作品设置中更新后的简介。');
  const icon=await page.request.get(base+'/icon.png');expect(icon.ok()).toBe(true);
  await editor.getByLabel('上传封面（非必要）').setInputFiles({name:'cover.png',mimeType:'image/png',buffer:await icon.body()});
  await page.screenshot({path:info.outputPath('edit.png')});
  await editor.getByRole('button',{name:'保存',exact:true}).click();
  await expect(editor).toHaveCount(0);
  card=page.locator('.writer-work').filter({hasText:edited});
  await expect(card).toBeVisible();
  const after=await(await page.request.get(base+'/api/manuscripts/'+key)).json();
  expect(after.title).toBe(edited);expect(after.description).toBe('在作品设置中更新后的简介。');expect(after.cover_image).toBeTruthy();
  expect(after.chapters).toEqual(before.chapters);expect(after.revision).toBe(before.revision+1);
  await card.getByRole('button',{name:'创作',exact:true}).click();
  await expect(page.locator('.manuscript-book-summary')).toContainText(edited);
  await expect(page.getByLabel('简介',{exact:true})).toHaveCount(0);
  await page.getByRole('checkbox').check();
  const published=page.waitForResponse(r=>r.request().method()==='PUT' && r.url().endsWith('/api/manuscripts/'+key));
  await page.getByRole('button',{name:'提交作品',exact:true}).click();
  const bookId=(await(await published).json()).bookId;
  const chapters=await(await page.request.get(base+'/api/books/'+bookId+'/chapters')).json();
  await card.getByRole('button',{name:'创作',exact:true}).click();
  await expect(page.locator('.writer-manager')).toBeVisible();
  await expect(page.getByText('书籍信息设置',{exact:false})).toHaveCount(0);
  await expect(page.getByLabel('更换书籍封面')).toHaveCount(0);
  await page.getByRole('button',{name:'关闭作品管理'}).click();
  await card.getByLabel(`管理《${edited}》`).click();
  await card.getByRole('button',{name:'编辑作品'}).click();
  await expect(editor.locator('form')).toHaveAttribute('data-busy','false');
  await editor.getByLabel('简介',{exact:true}).fill('已发布作品的新简介。');
  await editor.getByRole('button',{name:'移除封面'}).click();
  await editor.getByRole('button',{name:'保存',exact:true}).click();
  await expect(editor).toHaveCount(0);
  const book=await(await page.request.get(base+'/api/books/'+bookId)).json();
  expect(book.description).toBe('已发布作品的新简介。');expect(book.cover_image).toBe('');expect(book.visibility).not.toBe('private');
  expect(await(await page.request.get(base+'/api/books/'+bookId+'/chapters')).json()).toEqual(chapters);
});

test('cancel and conflicting metadata edits preserve the latest manuscript',async({page})=>{
  const title='冲突'+Date.now().toString().slice(-8);
  const card=await create(page,title);
  const work=(await(await page.request.get(base+'/api/writer/works?limit=20')).json()).find((w:{title:string})=>w.title===title);
  await card.getByLabel(`管理《${title}》`).click();await card.getByRole('button',{name:'编辑作品'}).click();
  const editor=page.getByRole('dialog',{name:'编辑作品',exact:true});
  await expect(editor.locator('form')).toHaveAttribute('data-busy','false');
  await editor.getByLabel('简介',{exact:true}).fill('未保存的输入');
  let questions=0;
  const cancel=async(dialog:import('@playwright/test').Dialog)=>{questions++;await dialog.dismiss();};
  page.on('dialog',cancel);await page.goBack();
  await expect(editor.getByLabel('简介',{exact:true})).toHaveValue('未保存的输入');
  await expect.poll(()=>questions).toBe(1);page.off('dialog',cancel);
  const current=await(await page.request.get(base+'/api/manuscripts/'+work.manuscriptKey)).json();
  const csrf=await(await page.request.get(base+'/api/auth/csrf')).json();
  const response=await page.request.put(base+'/api/manuscripts/'+work.manuscriptKey,{headers:{origin:base,'x-csrf-token':csrf.csrfToken},multipart:{manuscript:JSON.stringify({...current,description:'另一页面保存的新内容',action:'draft'})}});
  expect(response.ok()).toBe(true);
  await editor.getByRole('button',{name:'保存',exact:true}).click();
  await expect(editor.getByRole('alert')).toContainText('另一页面更新');
  await expect(editor.getByLabel('简介',{exact:true})).toHaveValue('未保存的输入');
  expect((await(await page.request.get(base+'/api/manuscripts/'+work.manuscriptKey)).json()).description).toBe('另一页面保存的新内容');
  page.once('dialog',async dialog=>{questions++;await dialog.accept();});
  await editor.getByRole('button',{name:'关闭编辑作品'}).click();
  await expect(editor).toHaveCount(0);expect(questions).toBe(2);
});
