import {test,expect,type Page} from '@playwright/test';
const base=process.env.MANUSCRIPT_BASE_URL || 'http://127.0.0.1:3107';
test.beforeEach(async({page})=>{
  const csrf=await(await page.request.get(base+'/api/auth/csrf')).json();
  const login=await page.request.post(base+'/api/auth/signin',{headers:{origin:base,'x-csrf-token':csrf.csrfToken},data:{email:'manuscript@example.test',password:'Manuscript-test-123'}});
  expect(login.ok()).toBe(true);
});
async function create(page:Page,title:string) {
  await page.goto(base+'/writer?action=new');
  await page.getByLabel('书名',{exact:true}).fill(title);
  await page.getByLabel('简介',{exact:true}).fill('故事的第一段简介。');
  await page.getByRole('button',{name:'创建',exact:true}).click();
  await expect(page).toHaveURL(base+'/writer');
  return page.locator('.writer-work').filter({hasText:title});
}
for(const width of [320,1440]) test(`metadata editing preserves draft chapters and published status at ${width}`,async({page},info)=>{
  await page.setViewportSize({width,height:844});
  const title='资料'+width+Date.now().toString().slice(-5), edited=title+'新';
  let card=await create(page,title);
  const works=await(await page.request.get(base+'/api/writer/works?limit=20')).json();
  const key=works.find((work:{title:string})=>work.title===title).manuscriptKey;
  await card.getByRole('button',{name:'创作',exact:true}).click();
  for (const [name, content] of [['第一章 来信', '不能丢失的第一章正文。'], ['第二章 远行', '不能丢失的第二章正文。']]) {
    await page.getByRole('button',{name:'新建章节',exact:true}).click();
    await page.getByLabel('章节名',{exact:true}).fill(name);
    await page.getByLabel('正文',{exact:true}).fill(content);
    await page.getByRole('button',{name:'保存',exact:true}).click();
    await expect(page.getByText('已保存到本机',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'返回草稿箱',exact:true}).click();
    await expect(page.locator('.writing-editor')).toHaveCount(0);
  }
  await page.getByRole('button',{name:'返回创作中心',exact:true}).click();
  const before=await(await page.request.get(base+'/api/manuscripts/'+key)).json();
  await card.getByLabel(`管理《${title}》`).click();
  await card.getByRole('button',{name:'编辑作品',exact:true}).click();
  const editor=page.getByRole('dialog',{name:'编辑作品',exact:true});
  await expect(editor.locator('form')).toHaveAttribute('data-busy','false');
  await editor.getByLabel('书名',{exact:true}).fill(edited);
  await editor.getByLabel('简介',{exact:true}).fill('在作品设置中更新后的简介。');
  const icon=await page.request.get(base+'/icon.png');expect(icon.ok()).toBe(true);
  await editor.getByLabel('上传封面（非必要）').setInputFiles({name:'cover.png',mimeType:'image/png',buffer:await icon.body()});
  await page.screenshot({path:info.outputPath('edit.png')});
  await editor.getByRole('button',{name:'保存',exact:true}).click();
  await expect(editor).toHaveCount(0);
  card=page.locator('.writer-work').filter({hasText:edited});
  await expect(card).toBeVisible();
  const after=await(await page.request.get(base+'/api/manuscripts/'+key)).json();
  expect(after.title).toBe(edited);expect(after.description).toBe('在作品设置中更新后的简介。');expect(after.cover_image).toBeTruthy();
  expect(after.chapters).toBeUndefined();expect(after.revision).toBe(before.revision+1);
  await card.getByRole('button',{name:'创作',exact:true}).click();
  await expect(page.locator('.writing-heading h2')).toContainText(edited);
  await expect(page.getByLabel('简介',{exact:true})).toHaveCount(0);
  await expect(page.locator('.writing-chapters li')).toHaveCount(2);
  await page.locator('.writing-chapter').filter({hasText:'第一章 来信'}).click();
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('不能丢失的第一章正文。');
  page.once('dialog',dialog=>dialog.accept());
  const published=page.waitForResponse(r=>r.request().method()==='POST' && r.url().includes('/workspace/') && r.url().endsWith('/publish'));
  await page.getByRole('button',{name:'发布',exact:true}).click();
  const bookId=(await(await published).json()).bookId;
  await expect(page.locator('.writing-editor')).toHaveCount(0);
  const chapters=await(await page.request.get(base+'/api/books/'+bookId+'/chapters')).json();
  expect(chapters).toHaveLength(1);
  await page.getByRole('tab',{name:/草稿箱/}).click();
  await expect(page.locator('.writing-chapters li')).toHaveCount(1);
  await expect(page.locator('.writing-chapters')).toContainText('第二章 远行');
  await page.getByRole('button',{name:'返回创作中心',exact:true}).click();
  await expect(card).toBeVisible();
  await card.getByLabel(`管理《${edited}》`).click();
  await card.getByRole('button',{name:'编辑作品'}).click();
  await expect(editor.locator('form')).toHaveAttribute('data-busy','false');
  await editor.getByLabel('简介',{exact:true}).fill('已发布作品的新简介。');
  await editor.getByRole('button',{name:'移除封面'}).click();
  await editor.getByRole('button',{name:'保存',exact:true}).click();
  await expect(editor).toHaveCount(0);
  const book=await(await page.request.get(base+'/api/books/'+bookId)).json();
  expect(book.description).toBe('已发布作品的新简介。');expect(book.cover_image).toBe('');expect(book.visibility).not.toBe('private');
  expect(await(await page.request.get(base+'/api/books/'+bookId+'/chapters')).json()).toEqual(chapters);
});

test('cancel and conflicting metadata edits preserve the latest manuscript',async({page})=>{
  const title='冲突'+Date.now().toString().slice(-8);
  const card=await create(page,title);
  const work=(await(await page.request.get(base+'/api/writer/works?limit=20')).json()).find((w:{title:string})=>w.title===title);
  await card.getByLabel(`管理《${title}》`).click();await card.getByRole('button',{name:'编辑作品'}).click();
  const editor=page.getByRole('dialog',{name:'编辑作品',exact:true});
  await expect(editor.locator('form')).toHaveAttribute('data-busy','false');
  await editor.getByLabel('简介',{exact:true}).fill('未保存的输入');
  let questions=0;
  const cancel=async(dialog:import('@playwright/test').Dialog)=>{questions++;await dialog.dismiss();};
  page.on('dialog',cancel);await page.goBack();
  await expect(editor.getByLabel('简介',{exact:true})).toHaveValue('未保存的输入');
  await expect.poll(()=>questions).toBe(1);page.off('dialog',cancel);
  const current=await(await page.request.get(base+'/api/manuscripts/'+work.manuscriptKey)).json();
  const csrf=await(await page.request.get(base+'/api/auth/csrf')).json();
  const response=await page.request.put(base+'/api/manuscripts/'+work.manuscriptKey,{headers:{origin:base,'x-csrf-token':csrf.csrfToken},multipart:{manuscript:JSON.stringify({...current,description:'另一页面保存的新内容',action:'draft'})}});
  expect(response.ok()).toBe(true);
  await editor.getByRole('button',{name:'保存',exact:true}).click();
  await expect(editor.getByRole('alert')).toContainText('另一页面更新');
  await expect(editor.getByLabel('简介',{exact:true})).toHaveValue('未保存的输入');
  expect((await(await page.request.get(base+'/api/manuscripts/'+work.manuscriptKey)).json()).description).toBe('另一页面保存的新内容');
  page.once('dialog',async dialog=>{questions++;await dialog.accept();});
  await editor.getByRole('button',{name:'关闭编辑作品'}).click();
  await expect(editor).toHaveCount(0);expect(questions).toBe(2);
});

test('administrator searches, edits and withdraws chapters through the shared editor', async ({page})=>{
  await page.setViewportSize({width:1440,height:900});
  const title='校对'+Date.now().toString().slice(-8);
  await create(page,title);
  const work=(await(await page.request.get(base+'/api/writer/works?limit=20')).json()).find((w:{title:string})=>w.title===title);
  const csrf=await(await page.request.get(base+'/api/auth/csrf')).json();
  const published=await page.request.post(base+`/api/writer/workspace/m_${work.manuscriptKey}/publish`,{headers:{origin:base,'x-csrf-token':csrf.csrfToken},data:{id:'admin-fixture',title:'第一章 校对',content:'待校对正文',number:1}});
  expect(published.ok()).toBe(true);
  const {chapterId}=await published.json();
  await page.reload();
  await page.getByRole('button',{name:'书籍总编辑',exact:true}).click();
  await page.getByPlaceholder('搜索书名或作者...').fill(title);
  const result=page.locator('div.group.items-start').filter({hasText:title}).last();
  await result.getByRole('button',{name:'管理',exact:true}).click();
  await expect(page.getByRole('tab',{name:/已发布/})).toHaveAttribute('aria-selected','true');
  await page.getByLabel('搜索章节').fill('不存在');
  await page.getByRole('button',{name:'搜索',exact:true}).click();
  await expect(page.locator('.writing-chapter')).toHaveCount(0);
  await page.getByLabel('搜索章节').fill('校对');
  await page.getByLabel('章节排序').selectOption('asc');
  await page.locator('.writing-chapter').click();
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('待校对正文');
  await page.getByLabel('正文',{exact:true}).fill('校对后的正文');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  expect((await(await page.request.get(base+'/api/chapters/'+chapterId)).json()).content).toBe('待校对正文');
  page.once('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'发布',exact:true}).click();
  await expect(page.locator('.writing-editor')).toHaveCount(0);
  expect((await(await page.request.get(base+'/api/chapters/'+chapterId)).json()).content).toBe('校对后的正文');
  await page.getByRole('button',{name:'批量管理',exact:true}).click();
  await page.getByRole('button',{name:'全选',exact:true}).click();
  await page.getByRole('region',{name:'章节批量管理'}).getByRole('button',{name:'删除',exact:true}).click();
  await page.getByRole('button',{name:'确认删除',exact:true}).click();
  await expect(page.locator('.writing-chapter')).toHaveCount(0);
  await page.getByRole('button',{name:'返回书籍总编辑'}).click();
  await expect(page.getByPlaceholder('搜索书名或作者...')).toBeVisible();
});
