import '../../tools/test-env.cjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import mongoose from 'mongoose';
import {MongoMemoryServer} from 'mongodb-memory-server';
import {createApp} from '../app.js';
import {readConfig} from '../config.js';
import Book from '../models/Book.js';
import Chapter from '../models/Chapter.js';

test('sitemap pages fetch only ordered public chapter IDs in one bounded query and reflect publishing changes',async t=>{
  const mongo=await MongoMemoryServer.create({binary:{version:'7.0.40'}});
  const config=readConfig({APP_ENV:'test',DATABASE_URL:mongo.getUri('test1_test'),JWT_SECRET:crypto.randomBytes(48).toString('hex')});
  await mongoose.connect(config.uri,{autoIndex:false,monitorCommands:true});
  await Chapter.createIndexes();
  const book=await Book.create({title:'Sitemap projection'}),empty=await Book.create({title:'Empty public work'});
  const chapters=await Chapter.insertMany(Array.from({length:1105},(_,i)=>({bookId:book._id,title:'Chapter '+i,chapter_number:2*i+1,content:'not part of a sitemap',deletedAt:i===2?new Date():null})));
  const server=createApp(config).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await mongoose.disconnect();await mongo.stop();});
  const base='http://127.0.0.1:'+server.address().port+'/api/books/',path=base+book._id+'/sitemap-chapters',commands=[];
  mongoose.connection.getClient().on('commandStarted',event=>{if(event.command.find==='chapters'||event.command.aggregate==='chapters')commands.push(event.command);});
  const get=async(url)=>{const response=await fetch(url);assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');return response.json();};
  const ids=chapters.filter((_,i)=>i!==2).map(c=>String(c._id));
  assert.deepEqual(await get(path),ids.slice(0,1000));
  assert.equal(commands.length,1);assert.equal(commands[0].find,'chapters');assert.deepEqual(commands[0].projection,{_id:1});assert.equal(commands[0].limit,1000);
  assert.deepEqual(await get(path+'?page=2'),ids.slice(1000));
  assert.deepEqual(await get(path+'?page=3'),[]);assert.deepEqual(await get(base+empty._id+'/sitemap-chapters'),[]);
  for(const page of ['0','-1','1.5','20001','one'])assert.equal((await fetch(path+'?page='+page)).status,400);
  assert.equal((await fetch(base+'f'.repeat(24)+'/sitemap-chapters')).status,404);
  const added=await Chapter.create({bookId:book._id,title:'New chapter',chapter_number:3000,content:'new'});
  assert.equal((await get(path+'?page=2')).at(-1),String(added._id));
  await Chapter.updateOne({_id:chapters[0]._id},{$set:{deletedAt:new Date()}});
  assert.equal((await get(path))[0],ids[1]);
  await Chapter.updateOne({_id:chapters[0]._id},{$set:{deletedAt:null}});
  assert.equal((await get(path))[0],ids[0]);
  const reader=await fetch(base+book._id+'/chapters?limit=2').then(r=>r.json());
  assert.equal(reader[0].title,'Chapter 0');assert.ok(Object.hasOwn(reader[0],'chapter_number'));
  await Book.updateOne({_id:book._id},{$set:{visibility:'private'}});assert.equal((await fetch(path)).status,404);
  await Book.updateOne({_id:book._id},{$set:{visibility:'public'}});assert.equal((await get(path))[0],ids[0]);
  await Book.updateOne({_id:book._id},{$set:{deletedAt:new Date()}});assert.equal((await fetch(path)).status,404);
});
